const CONFIG={"id":"source-sprint","title":"Source Sprint","subtitle":"Stimulus-based Regents MCQs only: read the document, answer fast, and learn from misses.","mode":"source","bank":"regents","gameType":"Regents Quick Play","categories":["Stimulus MCQ","Regents","Source Practice","Timed Sprint"],"accent":"#62e9ff","glyph":"DBQ","timeLimit":180};
const state={bank:null,questions:[],pool:[],current:null,score:0,streak:0,answered:0,missed:0,start:0,deadline:0,timer:null,locked:false};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const ICONS=typeof window!=="undefined"&&window.MrMacsIcons?window.MrMacsIcons:null;
const icon=name=>ICONS&&ICONS.has(name)?ICONS.svg(name):"";
function emptyState({iconName,title,sub,variant}){return '<div class="empty-state'+(variant?' '+variant:'')+'" role="status"><div class="empty-icon">'+icon(iconName||"scroll")+'</div><div class="empty-title">'+title+'</div>'+(sub?'<div class="empty-sub">'+sub+'</div>':'')+'</div>'}
const SourceBank=typeof window!=="undefined"?window.MrMacsSourceBank:null;
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const norm=v=>String(v||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
function shuffle(a){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function uniq(values){return[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}))}
function show(id){$$(".screen").forEach(s=>s.classList.remove("active"));$("#"+id).classList.add("active");scrollTo({top:0,behavior:"auto"})}
function fmt(sec){sec=Math.max(0,Math.floor(sec));return Math.floor(sec/60)+":"+String(sec%60).padStart(2,"0")}
function bankUrl(){return CONFIG.bank==="regents"?"../../data/regents-gauntlet-bank.json?v=20260502-source-contract":"../../data/chrono-defense-bank.json?v=20260502-source-contract"}
function rawQuestions(){return CONFIG.bank==="regents"?(state.bank.questions||[]):((state.bank.questions||[]).filter(q=>q.answer||q.choices))}
function stimulusImages(q){return SourceBank?SourceBank.stimulusImages(q):(q.stimulusImages||[]).filter(img=>img&&img.src)}
function hasStimulusImages(q){return SourceBank?SourceBank.hasStimulusImages(q):stimulusImages(q).length>0}
function sourceBased(q){return SourceBank?SourceBank.sourceBased(q):(hasStimulusImages(q)||q.stimulusRequired||/based on|according to|document|map|cartoon|graph|chart|excerpt|passage|photograph|source/i.test(q.stem||q.prompt||""))}
function quarantinedSource(q){return SourceBank?SourceBank.isQuarantined(q):/^quarantined/i.test(String(q.sourceIntegrity||""))}
function trustedSource(q){return SourceBank?SourceBank.trustedSource(q):(!quarantinedSource(q)&&hasStimulusImages(q))}
function usableQuestion(q){return CONFIG.bank!=="regents"||(SourceBank?SourceBank.usableRegentsQuestion(q):(!quarantinedSource(q)&&(!sourceBased(q)||hasStimulusImages(q))))}
function sourceLock(q){return SourceBank?SourceBank.sourceLock(q):{ok:trustedSource(q),needed:sourceBased(q),reason:trustedSource(q)?"":"Source needs review",images:trustedSource(q)?stimulusImages(q):[],identity:[q.course,q.source,(q.stimulusImages||[]).map(img=>img.src).join("|")].join("::"),label:trustedSource(q)?"Source matched":"Source blocked"}}
function promptText(q){return SourceBank?.displayPrompt?SourceBank.displayPrompt(q):String(q?.prompt||q?.stem||"").trim()}
function sourceText(q){return SourceBank?.displaySource?SourceBank.displaySource(q):String(q?.source||q?.category||"").trim()}
function stimulusLabel(q,img){return SourceBank?.displayStimulusLabel?SourceBank.displayStimulusLabel(q,img):String(img?.label||q?.source||"Source").trim()}
function studentLockLabel(lock){if(!lock)return"";if(lock.ok&&lock.needed)return"Source matched";if(lock.ok)return"No source needed";return"Source not ready"}
function hydrate(){state.questions=rawQuestions().filter(q=>usableQuestion(q)&&(CONFIG.mode!=="source"||trustedSource(q)));const courses=uniq(state.questions.map(q=>q.course));$("#courseSelect").innerHTML=["All Courses",...courses].map(c=>'<option>'+esc(c)+'</option>').join("");updateSets();$("#courseSelect").addEventListener("change",updateSets);$("#bankMetrics").innerHTML=[[state.questions.length,"questions ready"],[courses.length,"courses"],[CONFIG.timeLimit?fmt(CONFIG.timeLimit):"open","timer"]].map(m=>'<div class="metric"><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></div>').join("");$("#modeNotes").innerHTML=CONFIG.mode==="vocab"?'<p>Type the answer. Exact answers and listed aliases count; use Reveal when stuck, then keep moving.</p>':CONFIG.mode==="source"?'<p>Read the source image, title, caption, date, and speaker before choosing an answer.</p>':'<p>Questions come from the full review library. Review clues become four-choice checks with nearby terms as distractors.</p>';topStats()}
function updateSets(){const course=$("#courseSelect").value;const qs=state.questions.filter(q=>course==="All Courses"||q.course===course);const sets=uniq(qs.map(q=>q.set||q.day||q.subject));$("#setSelect").innerHTML=["All Sets",...sets].map(s=>'<option>'+esc(s)+'</option>').join("")}
function filtered(){const course=$("#courseSelect").value;const set=$("#setSelect").value;return state.questions.filter(q=>(course==="All Courses"||q.course===course)&&(set==="All Sets"||(q.set||q.day||q.subject)===set))}
function makeMcq(q){const lock=sourceLock(q);if(q.choices&&q.choices.length){const correct=(q.choices||[]).find(c=>String(c.label)===String(q.correct));return {kind:"mcq",prompt:promptText(q),choices:shuffle(q.choices.map(c=>({text:c.text,correct:String(c.label)===String(q.correct)}))),answer:correct?.text||"",explanation:q.explanation||"",course:q.course,set:q.set||q.day,source:sourceText(q),raw:q,images:lock.images,sourceLock:lock}}const same=state.questions.filter(x=>x.course===q.course&&x.answer&&x.answer!==q.answer);const distractors=shuffle(same).slice(0,3).map(x=>x.answer);return {kind:"mcq",prompt:promptText(q),choices:shuffle([q.answer,...distractors]).map(text=>({text,correct:text===q.answer})),answer:q.answer,explanation:q.explanation||"",course:q.course,set:q.set||q.day,source:sourceText(q),raw:q,images:[],sourceLock:lock}}
function makeVocab(q){return {kind:"vocab",prompt:promptText(q),answer:q.answer||((q.choices||[]).find(c=>String(c.label)===String(q.correct))?.text||""),aliases:q.aliases||[],explanation:q.explanation||"",course:q.course,set:q.set||q.day,source:sourceText(q),raw:q,images:q.stimulusImages||[]}}
function nextQuestion(){state.locked=false;if(!state.pool.length)state.pool=shuffle(filtered());if(!state.pool.length){if(state.answered===0){$("#stimulus").innerHTML="";$("#answerArea").innerHTML=emptyState({iconName:"scroll",title:"No source-based questions in this set",sub:"Try a different course or set on the Setup screen, then start again."});$("#prompt").textContent="Empty queue";$("#feedback").textContent="";return}finish();return}const raw=state.pool.pop();state.current=CONFIG.mode==="vocab"?makeVocab(raw):makeMcq(raw);renderQuestion()}
function renderStimulus(q){const lock=q.sourceLock||{ok:!!q.images?.length,needed:!!q.images?.length,reason:""};const lockIcon=lock.ok?icon("shield"):icon("warning");const badge='<div class="source-lock-pill '+(lock.ok?"ok":"warn")+'" data-source-identity="'+esc(lock.identity||"")+'">'+lockIcon+'<span>'+esc(studentLockLabel(lock))+(lock.reason?' · '+esc(lock.reason):"")+'</span></div>';$("#stimulus").innerHTML=q.images?.length?badge+'<div class="stimulus-grid">'+q.images.map(img=>'<figure><img src="'+esc(img.src)+'" alt="'+esc(stimulusLabel(q.raw||q,img))+'"><figcaption class="source-line">'+esc(stimulusLabel(q.raw||q,img))+'</figcaption></figure>').join("")+'</div>':(lock.needed?badge:"")}
function renderQuestion(){const q=state.current;$("#questionMeta").textContent=[q.course,q.set,q.source].filter(Boolean).join(" · ");$("#prompt").textContent=q.prompt;$("#feedback").textContent="";renderStimulus(q);if(q.kind==="vocab"){$("#answerArea").innerHTML='<div class="type-row"><input id="answerInput" autocomplete="off" placeholder="Type the answer"><button class="btn primary" id="checkBtn" type="button">Check</button><button class="btn ghost" id="revealBtn" type="button">Reveal</button></div>';$("#answerInput").focus();$("#checkBtn").onclick=checkTyped;$("#revealBtn").onclick=()=>grade(false,true);$("#answerInput").addEventListener("keydown",e=>{if(e.key==="Enter")checkTyped()})}else{$("#answerArea").innerHTML='<div class="choice-grid">'+q.choices.map((c,i)=>'<button class="choice" data-index="'+i+'"><strong>'+String.fromCharCode(65+i)+'.</strong> '+esc(c.text)+'</button>').join("")+'</div>';$$(".choice").forEach(btn=>btn.onclick=()=>grade(q.choices[Number(btn.dataset.index)].correct,false,btn))}}
function checkTyped(){const q=state.current;const value=norm($("#answerInput").value);const ok=[q.answer,...(q.aliases||[])].some(a=>norm(a)===value||value&&norm(a).includes(value)&&value.length>=5);grade(ok,false)}
function grade(ok,revealed,button){if(state.locked)return;state.locked=true;state.answered++;if(ok){state.streak++;state.score+=10+Math.min(30,state.streak*2)}else{state.streak=0;state.missed++}if(button){button.classList.add(ok?"correct":"wrong");$$(".choice").forEach((b,i)=>{if(state.current.choices[i].correct)b.classList.add("correct")})}$("#feedback").innerHTML='<strong>'+esc(ok?"Correct":revealed?"Revealed":"Not yet")+'</strong><br>Answer: '+esc(state.current.answer)+'<br>'+esc(state.current.explanation||"Review this item and try another one.");topStats();setTimeout(nextQuestion,ok?850:1500)}
function topStats(){const left=state.deadline?Math.max(0,Math.floor((state.deadline-Date.now())/1000)):0;$("#score").textContent=state.score;$("#streak").textContent=state.streak;$("#answered").textContent=state.answered;$("#clock").textContent=state.deadline?fmt(left):"--";$("#topStats").innerHTML=[state.score+" pts",state.streak+" streak",state.answered+" answered"].map(x=>'<span>'+esc(x)+'</span>').join("")}
function start(){state.pool=shuffle(filtered());state.score=0;state.streak=0;state.answered=0;state.missed=0;state.start=Date.now();state.deadline=CONFIG.timeLimit?Date.now()+CONFIG.timeLimit*1000:0;if(state.timer)clearInterval(state.timer);state.timer=setInterval(()=>{topStats();if(state.deadline&&Date.now()>=state.deadline)finish()},500);show("play");nextQuestion()}
function finish(){if(state.timer)clearInterval(state.timer);show("results");const pct=state.answered?Math.round((state.answered-state.missed)/state.answered*100):0;$("#resultTitle").textContent=CONFIG.title+" Results";$("#resultMetrics").innerHTML=[[state.score,"points"],[state.answered,"answered"],[pct+"%","accuracy"]].map(m=>'<div class="metric"><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></div>').join("");$("#coach").innerHTML=pct>=85?"Strong run. Move to a harder course set or a full exam.":pct>=65?"Good base. Replay the same course and slow down on misses.":"Use this as a warm-up: read the explanation, then replay with one course selected.";window.MrMacsAnalytics?.track("game_complete",{gameId:CONFIG.id,title:CONFIG.title,score:pct,questions:state.answered},{counter:"game-completions"})}
$("#bankMetrics").innerHTML=emptyState({iconName:"scroll",title:"Loading source bank…",sub:"Verifying every Regents stimulus before letting questions through."});
fetch(bankUrl()).then(r=>{if(!r.ok)throw new Error("HTTP "+r.status);return r.json()}).then(data=>{state.bank=data;hydrate()}).catch(err=>{console.error("[source-sprint] bank load failed",err);$("#bankMetrics").innerHTML=emptyState({iconName:"warning",title:"Couldn’t load the source bank",sub:"Check your connection and refresh the page. If this keeps happening, head back to the arcade and try another game.",variant:"error"});$("#modeNotes").innerHTML=""});
$("#startBtn").onclick=start;$("#skipBtn").onclick=nextQuestion;$("#finishBtn").onclick=finish;$("#againBtn").onclick=()=>{show("setup");hydrate()};
