const state={bank:null,course:"All Courses",set:"All Sets",length:20,timer:45,sound:true,audio:null,run:null,tick:null};
const $=s=>document.querySelector(s);
const $$=s=>Array.from(document.querySelectorAll(s));
function uniq(a){return Array.from(new Set(a.filter(Boolean))).sort((x,y)=>x.localeCompare(y,undefined,{numeric:true}))}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function shuffle(a){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function show(id){$$(".screen").forEach(s=>s.classList.remove("active"));$("#"+id).classList.add("active");scrollTo({top:0,behavior:"auto"})}
function questions(){return state.bank.questions.filter(q=>(state.course==="All Courses"||q.course===state.course)&&(state.set==="All Sets"||q.set===state.set))}
function tone(kind){if(!state.sound)return;try{state.audio=state.audio||new (window.AudioContext||window.webkitAudioContext)();const c=state.audio;const now=c.currentTime;const o=c.createOscillator();const g=c.createGain();const map={start:[392,523,.08,"triangle"],ok:[587,880,.13,"sine"],bad:[196,130,.18,"sawtooth"],tick:[740,740,.04,"square"],finish:[523,784,.18,"triangle"]};const m=map[kind]||map.ok;o.type=m[3];o.frequency.setValueAtTime(m[0],now);o.frequency.exponentialRampToValueAtTime(m[1],now+m[2]);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(kind==="bad"?.045:.028,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+m[2]);o.connect(g);g.connect(c.destination);o.start(now);o.stop(now+m[2]+.02)}catch(e){}}
function balancedPick(items,count){const groups=new Map();shuffle(items).forEach(q=>{const key=q.set||q.course;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(q)});const picked=[];while(picked.length<count&&Array.from(groups.values()).some(g=>g.length)){for(const group of groups.values()){if(group.length&&picked.length<count)picked.push(group.pop())}}return picked}
function renderSetup(){const qs=state.bank.questions;const stimulus=qs.filter(q=>(q.stimulusImages||[]).length).length;$("#topStats").innerHTML=[qs.length+" MCQs",stimulus+" source-page prompts",uniq(qs.map(q=>q.set)).length+" sets"].map(t=>'<span class="pill">'+esc(t)+'</span>').join("");$("#metrics").innerHTML=[[qs.length,"answer-keyed MCQs"],[stimulus,"embedded source pages"],[uniq(qs.map(q=>q.course)).length,"courses"],[uniq(qs.map(q=>q.set)).length,"review sets"]].map(m=>'<div class="metric"><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></div>').join("");$("#courseSelect").innerHTML=["All Courses"].concat(uniq(qs.map(q=>q.course))).map(c=>'<option>'+esc(c)+'</option>').join("");renderSetOptions();renderPreview();initFx()}
function renderSetOptions(){const sets=uniq(state.bank.questions.filter(q=>state.course==="All Courses"||q.course===state.course).map(q=>q.set));$("#setSelect").innerHTML=["All Sets"].concat(sets).map(s=>'<option>'+esc(s)+'</option>').join("");if(!["All Sets"].concat(sets).includes(state.set))state.set="All Sets";$("#setSelect").value=state.set}
function renderPreview(){const qs=questions();const count=state.length===999?qs.length:Math.min(state.length,qs.length);const stim=qs.filter(q=>(q.stimulusImages||[]).length).length;$("#availableCount").textContent=qs.length+" available";$("#preview").innerHTML='<strong>'+esc(count)+' questions queued</strong><br>'+esc(stim)+' source-page prompts in this pool.<br>'+esc(state.course)+' · '+esc(state.set)+'<br>'+esc(state.timer?state.timer+" seconds per question":"No timer")+' with instant scoring and explanations.'}
function start(){const pool=questions();if(!pool.length)return;const target=state.length===999?pool.length:Math.min(state.length,pool.length);state.run={items:balancedPick(pool,target),index:0,score:0,correct:0,played:0,streak:0,bestStreak:0,missed:[],answered:false,deadline:0,lastTick:99};tone("start");show("playScreen");renderQuestion()}
function current(){return state.run.items[state.run.index]}
function renderStimulus(q){const images=q.stimulusImages||[];$("#sourceMeta").textContent=q.source||"Original source page";$("#stimulusStrip").innerHTML=images.length?images.map((img,i)=>'<figure class="stimulus-page"><img src="'+esc(img.src)+'" alt="'+esc(img.label||("Stimulus page "+(i+1)))+'" loading="eager"><figcaption>'+esc(img.label||("Stimulus page "+(i+1)))+'</figcaption></figure>').join(""):'<div class="preview"><strong>No separate source page for this item.</strong><br>This question is direct content recall from the selected review set.</div>'}
function renderQuestion(){const r=state.run,q=current();r.answered=false;r.lastTick=99;$("#progressText").textContent=(r.index+1)+" / "+r.items.length;$("#progressFill").style.width=(r.index/r.items.length*100)+"%";$("#setText").textContent=q.set;$("#questionTags").innerHTML=[q.course,q.day,q.set,q.stimulusRequired?"Stimulus Based":"Content MCQ"].map(t=>'<span class="tag">'+esc(t)+'</span>').join("");$("#questionStem").textContent=q.stem;$("#choices").innerHTML=q.choices.map(c=>'<button class="choice" type="button" data-choice="'+esc(c.label)+'"><strong>'+esc(c.label)+'</strong><span>'+esc(c.text)+'</span></button>').join("");$("#feedback").className="feedback hidden";$("#nextBtn").classList.add("hidden");renderStimulus(q);renderHud();$$(".choice").forEach(btn=>btn.addEventListener("click",()=>choose(btn.dataset.choice,false)));startTimer()}
function renderHud(){const r=state.run;const acc=r.played?Math.round(r.correct/r.played*100):0;$("#scoreText").textContent=r.score;$("#streakText").textContent=r.streak;$("#accuracyText").textContent=acc+"%"}
function startTimer(){clearTimer();if(!state.timer){$("#timeText").textContent="Off";$("#timerFill").style.transform="scaleX(1)";return}const r=state.run;r.deadline=performance.now()+state.timer*1000;tick();state.tick=setInterval(tick,180)}
function clearTimer(){if(state.tick){clearInterval(state.tick);state.tick=null}}
function remainingMs(){return Math.max(0,state.run.deadline-performance.now())}
function tick(){if(!state.run||state.run.answered)return;const left=remainingMs();const seconds=Math.ceil(left/1000);$("#timeText").textContent=seconds;$("#timerFill").style.transform="scaleX("+(left/(state.timer*1000))+")";if(seconds<=5&&seconds>0&&seconds!==state.run.lastTick){state.run.lastTick=seconds;tone("tick")}if(left<=0)choose(null,true)}
function choose(label,expired){const r=state.run,q=current();if(r.answered)return;r.answered=true;clearTimer();r.played++;const ok=!expired&&label===q.correct;$$(".choice").forEach(btn=>{btn.disabled=true;if(btn.dataset.choice===q.correct)btn.classList.add("correct");else if(btn.dataset.choice===label)btn.classList.add("wrong")});if(ok){r.correct++;r.streak++;r.bestStreak=Math.max(r.bestStreak,r.streak);const timeBonus=state.timer?Math.ceil(remainingMs()/1000)*2:0;const points=100+Math.min(180,r.streak*18)+timeBonus;r.score+=points;feedback("correct","Correct",q,"+"+points+" points. Streak bonus is active.");tone("ok")}else{r.streak=0;r.score=Math.max(0,r.score-25);r.missed.push({q:q,choice:label,expired:expired});feedback("wrong",expired?"Time Expired":"Missed",q,expired?"The correct answer is highlighted below.":"Review the correct answer and explanation below.");tone("bad")}$("#nextBtn").classList.remove("hidden");renderHud();$("#progressFill").style.width=((r.index+1)/r.items.length*100)+"%";if(r.index>=r.items.length-1)$("#nextBtn").textContent="Results";else $("#nextBtn").textContent="Next"}
function feedback(kind,title,q,note){const correct=q.choices.find(c=>c.label===q.correct);$("#feedback").className="feedback "+kind;$("#feedback").innerHTML='<strong>'+esc(title)+'</strong><p>'+esc(note)+'</p><p><strong>'+esc(q.correct)+'. '+esc(correct?correct.text:"")+'</strong></p><p>'+esc(q.explanation||"Review the source page and connect it to the correct historical content.")+'</p>'}
function next(){const r=state.run;if(!r||!r.answered)return;if(r.index>=r.items.length-1)return finish();r.index++;renderQuestion()}
function finish(){if(!state.run)return;clearTimer();tone("finish");const r=state.run;show("summaryScreen");const acc=r.played?Math.round(r.correct/r.played*100):0;$("#summaryMetrics").innerHTML=[[r.score,"final score"],[acc+"%","accuracy"],[r.correct+"/"+r.played,"correct"],[r.bestStreak,"best streak"]].map(m=>'<div class="metric"><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></div>').join("");$("#missedList").innerHTML=r.missed.length?r.missed.map(item=>{const q=item.q;const right=q.choices.find(c=>c.label===q.correct);return '<div class="missed-item"><strong>'+esc(q.stem)+'</strong><p>'+esc(q.course+" · "+q.set+" · "+q.source)+'</p><p><strong>Correct:</strong> '+esc(q.correct+". "+(right?right.text:""))+'</p><p>'+esc(q.explanation||"Review this item again with the source page.")+'</p></div>'}).join(""):'<div class="missed-item"><strong>No missed questions.</strong><p>Run a longer mixed sprint or switch courses for a harder review round.</p></div>'}
function initFx(){if(matchMedia("(prefers-reduced-motion: reduce)").matches||innerWidth<880)return;const canvas=$("#fx"),ctx=canvas.getContext("2d");let sparks=[];function resize(){const scale=Math.min(devicePixelRatio||1,1.25);canvas.width=Math.floor(innerWidth*scale);canvas.height=Math.floor(innerHeight*scale);sparks=Array.from({length:Math.min(80,Math.floor(innerWidth/18))},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,v:1+Math.random()*4,l:18+Math.random()*70,h:Math.random()}))}function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.globalCompositeOperation="screen";for(const s of sparks){s.x+=s.v*2;s.y+=Math.sin(s.x*.01)*.2;if(s.x>canvas.width+s.l){s.x=-s.l;s.y=Math.random()*canvas.height}const grad=ctx.createLinearGradient(s.x-s.l,s.y,s.x,s.y);grad.addColorStop(0,"rgba(101,242,255,0)");grad.addColorStop(1,s.h>.72?"rgba(255,211,106,.35)":"rgba(101,242,255,.32)");ctx.strokeStyle=grad;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(s.x-s.l,s.y);ctx.lineTo(s.x,s.y);ctx.stroke()}requestAnimationFrame(draw)}resize();addEventListener("resize",resize);draw()}
fetch("../../data/regents-gauntlet-bank.json?v=20260426-source-sprint").then(r=>r.json()).then(bank=>{state.bank=bank;renderSetup()});
$("#courseSelect").addEventListener("change",e=>{state.course=e.target.value;state.set="All Sets";renderSetOptions();renderPreview()});
$("#setSelect").addEventListener("change",e=>{state.set=e.target.value;renderPreview()});
$("#lengthSelect").addEventListener("change",e=>{state.length=Number(e.target.value);renderPreview()});
$("#timerSelect").addEventListener("change",e=>{state.timer=Number(e.target.value);renderPreview()});
$("#startBtn").addEventListener("click",start);
$("#mixedBtn").addEventListener("click",()=>{state.course="All Courses";state.set="All Sets";state.length=40;state.timer=45;$("#courseSelect").value=state.course;$("#lengthSelect").value="40";$("#timerSelect").value="45";renderSetOptions();renderPreview();start()});
$("#nextBtn").addEventListener("click",next);
$("#quitBtn").addEventListener("click",finish);
$("#againBtn").addEventListener("click",start);
$("#setupBtn").addEventListener("click",()=>{clearTimer();show("setupScreen")});
$("#backBtn").addEventListener("click",()=>{location.href="../../index.html"});
$("#soundBtn").addEventListener("click",()=>{state.sound=!state.sound;$("#soundBtn").textContent=state.sound?"Sound On":"Sound Off";tone("ok")});
$("#stimulusToggle").addEventListener("click",()=>{const panel=$("#stimulusPanel");panel.classList.toggle("expanded");$("#stimulusToggle").textContent=panel.classList.contains("expanded")?"Close":"Focus"});
addEventListener("keydown",e=>{if(!state.run||!document.querySelector("#playScreen.active"))return;const key=e.key.toUpperCase();if(["1","2","3","4","A","B","C","D"].includes(key)){const btn=$('.choice[data-choice="'+key+'"]');if(btn)btn.click()}if(e.key==="Enter"&&!$("#nextBtn").classList.contains("hidden"))next()});
