
const state={bank:null,course:"All Courses",set:"All Sets",length:25,mode:"solo",run:null,sound:null};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
function uniq(a){return[...new Set(a.filter(Boolean))].sort((x,y)=>x.localeCompare(y,undefined,{numeric:true}))}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function shuffle(a){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function show(id){$$(".screen").forEach(s=>s.classList.remove("active"));$("#"+id).classList.add("active");scrollTo({top:0,behavior:"auto"})}
function questions(){return state.bank.questions.filter(q=>(state.course==="All Courses"||q.course===state.course)&&(state.set==="All Sets"||q.set===state.set))}
function ping(type){try{state.sound=state.sound||new (window.AudioContext||window.webkitAudioContext)();const c=state.sound,o=c.createOscillator(),g=c.createGain();o.type=type==="ok"?"triangle":type==="bad"?"sawtooth":"sine";o.frequency.value=type==="ok"?740:type==="bad"?170:420;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(type==="bad"?.04:.028,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.18);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.2)}catch(e){}}
function balancedPick(items,count){const groups=new Map();shuffle(items).forEach(q=>{const key=q.set||q.course;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(q)});const picked=[];while(picked.length<count&&[...groups.values()].some(g=>g.length)){for(const group of groups.values()){if(group.length&&picked.length<count)picked.push(group.pop())}}return picked}
function renderSetup(){const qs=state.bank.questions;const stimulus=qs.filter(q=>q.stimulusImages&&q.stimulusImages.length).length;$("#topStats").innerHTML=[qs.length+" MCQs",stimulus+" with stimulus crops",uniq(qs.map(q=>q.set)).length+" sets"].map(t=>'<span class="pill">'+esc(t)+'</span>').join("");$("#metrics").innerHTML=[[qs.length,"answer-keyed MCQs"],[stimulus,"stimulus prompts"],[uniq(qs.map(q=>q.set)).length,"review sets"]].map(m=>'<div class="metric"><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></div>').join("");$("#courseSelect").innerHTML=["All Courses",...uniq(qs.map(q=>q.course))].map(c=>'<option>'+esc(c)+'</option>').join("");renderSetOptions();renderPreview()}
function renderSetOptions(){const sets=uniq(state.bank.questions.filter(q=>state.course==="All Courses"||q.course===state.course).map(q=>q.set));$("#setSelect").innerHTML=["All Sets",...sets].map(s=>'<option>'+esc(s)+'</option>').join("");if(!["All Sets",...sets].includes(state.set))state.set="All Sets";$("#setSelect").value=state.set}
function renderPreview(){const qs=questions();const count=state.length==999?qs.length:Math.min(Number(state.length),qs.length);const stim=qs.filter(q=>q.stimulusImages&&q.stimulusImages.length).length;$("#preview").innerHTML='<strong>'+esc(qs.length)+' available questions</strong><br>'+esc(stim)+' include cropped stimulus images.<br>'+esc(state.course)+' · '+esc(state.set)+'<br>This run will use '+count+' shuffled questions balanced across selected sets.';$("#modeSelect").value=state.mode;$("#teams").classList.toggle("hidden",state.mode!=="team")}
function start(){const pool=questions();const target=state.length==999?pool.length:Math.min(Number(state.length),pool.length);const selected=balancedPick(pool,target);state.run={items:selected,index:0,correct:0,missed:[],lives:3,streak:0,scores:(state.mode==="team"?["Team 1","Team 2"]:["Solo Player"]).map(()=>0),teams:state.mode==="team"?[$('[data-team="0"]').value||"Team 1",$('[data-team="1"]').value||"Team 2"]:["Solo Player"],active:0,answered:false};ping("start");show("battleScreen");renderQuestion()}
function current(){return state.run.items[state.run.index]}
function renderStimulus(q){const panel=$("#stimulusPanel"),strip=$("#stimulusStrip");const images=q.stimulusImages||[];panel.classList.toggle("hidden",!images.length);panel.classList.remove("expanded");strip.innerHTML=images.map((img,i)=>'<figure class="stimulus-page"><img src="'+esc(img.src)+'" alt="'+esc(img.label||("Stimulus image "+(i+1)))+'" loading="eager"><figcaption>'+esc(img.label||("Stimulus image "+(i+1)))+'</figcaption></figure>').join("")}
function renderQuestion(){const r=state.run,q=current();r.answered=false;$("#missionTitle").textContent=state.set==="All Sets"?state.course:state.set;$("#missionMeta").textContent=q.course+" · "+q.day+" · "+q.source;$("#progressText").textContent=(r.index+1)+" / "+r.items.length;$("#progressBar").style.width=(r.index/r.items.length*100)+"%";$("#livesText").textContent=r.lives;$("#livesBar").style.width=(r.lives/3*100)+"%";$("#streakText").textContent=r.streak;$("#streakBar").style.width=Math.min(100,r.streak*18)+"%";$("#questionTags").innerHTML=[q.course,q.set,q.stimulusRequired?"Stimulus Based":((q.stimulusImages||[]).length?"Stimulus":"Content Recall"),...q.tags.slice(0,2),"Active: "+r.teams[r.active]].map(t=>'<span class="tag">'+esc(t)+'</span>').join("");$("#questionStem").textContent=q.stem;renderStimulus(q);$("#choices").innerHTML=q.choices.map(c=>'<button class="choice" data-choice="'+esc(c.label)+'"><strong>'+esc(c.label)+'.</strong> '+esc(c.text)+'</button>').join("");$("#feedback").className="feedback hidden";$("#nextBtn").classList.add("hidden");renderScores();$$(".choice").forEach(b=>b.addEventListener("click",()=>choose(b.dataset.choice)))}
function renderScores(){const r=state.run;$("#scoreGrid").innerHTML=r.teams.map((t,i)=>'<div class="score-card '+(i===r.active?"active":"")+'"><span>'+esc(t)+'</span><strong>$'+r.scores[i]+'</strong></div>').join("")}
function choose(label){const r=state.run,q=current();if(r.answered)return;r.answered=true;const ok=label===q.correct;$$(".choice").forEach(b=>{b.disabled=true;if(b.dataset.choice===q.correct)b.classList.add("correct");else if(b.dataset.choice===label)b.classList.add("wrong")});if(ok){r.correct++;r.streak++;const points=100+Math.min(150,r.streak*15);r.scores[r.active]+=points;feedback("correct","Correct",q,"+"+points+" points");ping("ok")}else{r.streak=0;r.lives--;r.scores[r.active]-=25;r.missed.push(q);feedback("wrong","Missed",q,"Review the correct choice below.");ping("bad")}if(r.teams.length>1)r.active=(r.active+1)%r.teams.length;$("#nextBtn").classList.remove("hidden");renderScores();$("#livesText").textContent=r.lives;$("#livesBar").style.width=(r.lives/3*100)+"%";$("#streakText").textContent=r.streak;$("#streakBar").style.width=Math.min(100,r.streak*18)+"%"}
function feedback(kind,title,q,note){$("#feedback").className="feedback "+kind;const correct=q.choices.find(c=>c.label===q.correct);$("#feedback").innerHTML='<strong>'+esc(title)+'</strong><p>'+esc(note)+'</p><p><strong>'+esc(q.correct)+'. '+esc(correct?.text||"")+'</strong></p><p>'+esc(q.explanation)+'</p>'}
function next(){const r=state.run;if(r.lives<=0||r.index>=r.items.length-1)return finish();r.index++;$("#progressBar").style.width=(r.index/r.items.length*100)+"%";ping("start");renderQuestion()}
function finish(){const r=state.run;show("summaryScreen");const played=r.index+1;const acc=played?Math.round(r.correct/played*100):0;const winner=r.scores.reduce((best,score,i)=>score>r.scores[best]?i:best,0);window.MrMacsAnalytics?.track("game_complete",{gameId:"regents-gauntlet",title:"Regents Gauntlet",score:r.scores[winner],accuracy:acc,questions:played},{counter:"game-completions"});$("#summaryTitle").textContent=r.lives>0?"Gauntlet Complete":"Run Complete";$("#summaryMetrics").innerHTML=[[acc+"%","accuracy"],[r.correct+"/"+played,"correct"],[r.missed.length,"study targets"],[r.teams[winner]+" $"+r.scores[winner],"top score"]].map(m=>'<div class="metric"><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></div>').join("");$("#missedList").innerHTML=r.missed.length?r.missed.map(q=>'<div class="missed-item"><strong>'+esc(q.stem)+'</strong><p>'+esc(q.set+" · "+q.source)+'</p><p>'+esc(q.explanation)+'</p></div>').join(""):'<div class="missed-item"><strong>No missed questions.</strong><p>Try a longer mixed run to keep sharpening recall and source reading.</p></div>'}
function initCanvas(){const liteFx=new URLSearchParams(location.search).get("fx")!=="full";document.documentElement.classList.toggle("perf-lite",liteFx);if(liteFx||matchMedia("(prefers-reduced-motion: reduce)").matches||innerWidth<900){$("#fx").style.display="none";return}const c=$("#fx"),x=c.getContext("2d");let p=[];function resize(){const s=Math.min(devicePixelRatio||1,1.25);c.width=innerWidth*s;c.height=innerHeight*s;p=Array.from({length:Math.min(80,Math.floor(innerWidth/20))},()=>({x:Math.random()*c.width,y:Math.random()*c.height,r:.4+Math.random()*1.7,v:.12+Math.random()*.48,h:Math.random()}))}function draw(){x.clearRect(0,0,c.width,c.height);x.globalCompositeOperation="screen";for(const m of p){m.y+=m.v;if(m.y>c.height+8){m.y=-8;m.x=Math.random()*c.width}x.fillStyle=m.h>.66?"rgba(255,211,106,.48)":m.h>.33?"rgba(111,156,255,.36)":"rgba(94,231,255,.5)";x.beginPath();x.arc(m.x,m.y,m.r,0,Math.PI*2);x.fill()}requestAnimationFrame(draw)}resize();addEventListener("resize",resize);draw()}
fetch("../../data/regents-gauntlet-bank.json?v=20260427-us-review").then(r=>r.json()).then(bank=>{state.bank=bank;renderSetup();initCanvas()});
$("#courseSelect").addEventListener("change",e=>{state.course=e.target.value;state.set="All Sets";renderSetOptions();renderPreview()});
$("#setSelect").addEventListener("change",e=>{state.set=e.target.value;renderPreview()});
$("#lengthSelect").addEventListener("change",e=>{state.length=Number(e.target.value);renderPreview()});
$("#modeSelect").addEventListener("change",e=>{state.mode=e.target.value;renderPreview()});
$("#startBtn").addEventListener("click",start);
$("#randomBtn").addEventListener("click",()=>{state.course="All Courses";state.set="All Sets";state.length=25;$("#courseSelect").value=state.course;$("#lengthSelect").value="25";renderSetOptions();renderPreview()});
$("#nextBtn").addEventListener("click",next);
$("#quitBtn").addEventListener("click",finish);
$("#againBtn").addEventListener("click",start);
$("#setupBtn").addEventListener("click",()=>show("setupScreen"));
$("#stimulusToggle").addEventListener("click",()=>{const p=$("#stimulusPanel");p.classList.toggle("expanded");$("#stimulusToggle").textContent=p.classList.contains("expanded")?"Collapse":"Expand"});
