
const PROFILES={
  "Grade 10 Global History II":{
    id:"global-history-ii",
    label:"Global History II",
    title:"Global History II Practice Regents",
    writing:"CRQ + Enduring Issues Essay",
    shortTitle:"Part II: Document-Based CRQs",
    essayTitle:"Part III: Document-Based Enduring Issues Essay (5 Documents)",
    shortMax:6,
    essayMax:5,
    sectionTargets:{mcq:55,short:45,essay:70,review:10},
    issueTerms:["conflict","human rights","power","inequality","scarcity","migration","industrialization","nationalism","imperialism","technology","environment","belief systems"],
    courseTerms:["revolution","empire","imperialism","nationalism","industrialization","enlightenment","communism","democracy","human rights","genocide","decolonization","globalization"],
    shortTasks:[
      {points:3,title:"CRQ Set 1",prompts:["Describe the historical context surrounding Document 1.","Use evidence from Document 2 to explain the author or source's point of view, purpose, audience, or bias.","Explain a relationship between Documents 1 and 2, such as cause and effect, similarity, difference, or turning point."]},
      {points:3,title:"CRQ Set 2",prompts:["Identify the central issue or historical development shown in Document 3.","Use evidence from Document 4 to explain one impact of that development.","Explain how the documents connect to a larger Global History theme."]}
    ],
    essayPrompt:"Identify and define an enduring issue raised by the five documents. Argue why the issue has endured over time. Use evidence from at least three of the five documents and include outside information from Global History."
  },
  "Grade 11 U.S. History":{
    id:"us-history",
    label:"U.S. History",
    title:"U.S. History Practice Regents",
    writing:"Short Essays + Civic Literacy Essay",
    shortTitle:"Part II: Document-Based Short Essays",
    essayTitle:"Part III: Document-Based Civic Literacy Essay",
    shortMax:10,
    essayMax:5,
    sectionTargets:{mcq:55,short:50,essay:65,review:10},
    issueTerms:["constitutional principle","civic issue","federalism","civil liberties","civil rights","checks and balances","due process","equal protection","voting rights","presidential power","judicial review"],
    courseTerms:["constitution","amendment","supreme court","federalism","reform","civil rights","new deal","foreign policy","war","president","congress","citizenship"],
    shortTasks:[
      {points:5,title:"Short Essay 1",prompts:["Describe the historical context surrounding Documents 1 and 2.","Use evidence from both documents to explain how they are related by cause and effect, similarity, difference, or turning point.","Include one specific outside detail from U.S. History."]},
      {points:5,title:"Short Essay 2",prompts:["Describe the historical context surrounding Documents 3 and 4.","Use evidence from both documents to explain the relationship between the ideas or events shown.","Explain why this relationship mattered in U.S. History."]}
    ],
    essayPrompt:"Identify the constitutional or civic issue raised by the documents. Explain the historical circumstances surrounding the issue, describe efforts by people or government to address it, and discuss its impact on the United States. Use evidence from the documents and outside information."
  }
};

const state={bank:null,profile:null,exam:null,section:"mcq",mcqIndex:0,answers:{},marked:{},writing:{},startMs:0,deadlineMs:0,timeLimit:180,sectionMs:{mcq:0,short:0,essay:0,review:0},sectionStartedMs:0,submitted:false,timer:null,result:null};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const SAVE_KEY="mrmacs-regents-practice-exam-v1";
const COMMON=new Set("the a an and or but if then this that these those with from into onto about above below because while where when which what who whom whose are was were been being have has had will would could should may might can cannot one two three four document source passage excerpt cartoon map graph chart table author shows shown based according question answer choice".split(" "));

function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function norm(v){return String(v||"").toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim()}
function words(v){return norm(v).split(" ").filter(Boolean)}
function uniq(a){return[...new Set(a.filter(Boolean))]}
function shuffle(a){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function show(id){$$(".screen").forEach(s=>s.classList.remove("active"));$("#"+id).classList.add("active");scrollTo({top:0,behavior:"auto"})}
function fmt(sec){if(!Number.isFinite(sec)||sec<0)sec=0;const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=Math.floor(sec%60);return h?String(h)+":"+String(m).padStart(2,"0")+":"+String(s).padStart(2,"0"):String(m)+":"+String(s).padStart(2,"0")}
function sourceBased(q){return (q.stimulusImages&&q.stimulusImages.length)||q.stimulusRequired||/based on|according to|document|map|cartoon|graph|chart|excerpt|passage|photograph|source/i.test(q.stem)}
function courseQuestions(course){return state.bank.questions.filter(q=>q.course===course)}
function balancedPick(items,count){const groups=new Map();shuffle(items).forEach(q=>{const key=q.set||q.day||q.course;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(q)});const picked=[];while(picked.length<count&&[...groups.values()].some(g=>g.length)){for(const group of groups.values()){if(group.length&&picked.length<count)picked.push(group.pop())}}return picked}
function displayQuestion(q){const numeric=(q.choices||[]).every(c=>/^\d+$/.test(String(c.label)));const labels=numeric?["1","2","3","4"]:["A","B","C","D"];const choices=shuffle(q.choices||[]).map((choice,index)=>({...choice,originalLabel:String(choice.label),label:labels[index]||String(index+1)}));const correctChoice=choices.find(c=>c.originalLabel===String(q.correct));return {...q,originalCorrect:String(q.correct),displayedChoices:choices,correct:correctChoice?correctChoice.label:String(q.correct)}}
function keywordsFromDoc(doc){const raw=[doc.stem,doc.explanation,doc.source,(doc.tags||[]).join(" "),...(doc.choices||[]).map(c=>c.text)].join(" ");const all=words(raw).filter(w=>w.length>4&&!COMMON.has(w));const counts={};all.forEach(w=>counts[w]=(counts[w]||0)+1);return Object.entries(counts).sort((a,b)=>b[1]-a[1]||b[0].localeCompare(a[0])).slice(0,10).map(([w])=>w)}
function makeDoc(q,index){return {...q,docNumber:index+1,keywords:keywordsFromDoc(q)}}
function assembleExam(course,timeLimit){const profile=PROFILES[course];const all=courseQuestions(course);const sourced=all.filter(sourceBased);const direct=all.filter(q=>!sourceBased(q));let mcqPool=sourced.length>=28?sourced:sourced.concat(direct);const mcq=balancedPick(mcqPool,28).map(displayQuestion);const used=new Set(mcq.map(q=>q.id));let writingPool=sourced.filter(q=>!used.has(q.id));if(writingPool.length<9)writingPool=sourced;const writingDocs=balancedPick(writingPool,9).map(makeDoc);const shortDocs=writingDocs.slice(0,4);const essayDocs=writingDocs.slice(4,9);const shortTasks=profile.shortTasks.map((task,i)=>({...task,id:"short-"+(i+1),docs:shortDocs.slice(i*2,i*2+2)}));return {id:profile.id+"-"+Date.now(),course,profileId:profile.id,timeLimit:Number(timeLimit),builtAt:new Date().toISOString(),mcq,shortTasks,essay:{id:"essay",title:profile.essayTitle,points:profile.essayMax,prompt:profile.essayPrompt,docs:essayDocs}}}
function renderSetup(){const courses=Object.keys(PROFILES).filter(c=>courseQuestions(c).length);$("#courseSelect").innerHTML=courses.map(c=>'<option value="'+esc(c)+'">'+esc(PROFILES[c].label)+'</option>').join("");state.profile=PROFILES[courses[0]];const qs=state.bank.questions;const stim=qs.filter(sourceBased).length;$("#setupMetrics").innerHTML=[[qs.length,"released MCQs"],[stim,"source-based items"],["28 MCQs","document writing"]].map(m=>'<div class="metric"><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></div>').join("");renderPreview();$("#resumeBtn").classList.toggle("hidden",!loadSaved(false))}
function renderPreview(){const course=$("#courseSelect").value;const profile=PROFILES[course];const qs=courseQuestions(course);const stim=qs.filter(sourceBased).length;const total=28+profile.shortMax+profile.essayMax;$("#examPreview").innerHTML='<strong>'+esc(profile.title)+'</strong><br>'+esc(qs.length)+' released MCQs in this course bank; '+esc(stim)+' include source images.<br><br><strong>Exam build</strong><br>Part I: 28 MCQs<br>'+esc(profile.shortTitle)+': '+esc(profile.shortMax)+' approximate points<br>'+esc(profile.essayTitle)+': '+esc(profile.essayMax)+' approximate points<br><br><strong>Approximate raw scale</strong><br>'+total+' raw points converted to a 100-point practice estimate.'}
function startExam(){clearSaved();const course=$("#courseSelect").value;state.profile=PROFILES[course];state.timeLimit=Number($("#timerSelect").value);state.exam=assembleExam(course,state.timeLimit);state.section="mcq";state.mcqIndex=0;state.answers={};state.marked={};state.writing={};state.submitted=false;state.result=null;state.sectionMs={mcq:0,short:0,essay:0,review:0};state.startMs=Date.now();state.deadlineMs=state.timeLimit>0?state.startMs+state.timeLimit*60000:0;state.sectionStartedMs=Date.now();show("examScreen");renderExam();startTimer();saveProgress()}
function resumeExam(){const saved=loadSaved(true);if(!saved)return;show("examScreen");renderExam();startTimer()}
function loadSaved(apply){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return null;const saved=JSON.parse(raw);if(!saved.exam||saved.submitted)return null;if(apply){Object.assign(state,saved);state.profile=PROFILES[state.exam.course];state.sectionStartedMs=Date.now();}return saved}catch{return null}}
function saveProgress(){if(!state.exam||state.submitted)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify({exam:state.exam,profile:state.profile,section:state.section,mcqIndex:state.mcqIndex,answers:state.answers,marked:state.marked,writing:state.writing,startMs:state.startMs,deadlineMs:state.deadlineMs,timeLimit:state.timeLimit,sectionMs:currentSectionMs(),submitted:false}))}catch{}}
function clearSaved(){try{localStorage.removeItem(SAVE_KEY)}catch{}}
function currentSectionMs(){const copy={...state.sectionMs};if(state.sectionStartedMs&&copy[state.section]!=null)copy[state.section]+=Date.now()-state.sectionStartedMs;return copy}
function switchSection(section){if(state.submitted)return;state.sectionMs=currentSectionMs();state.sectionStartedMs=Date.now();state.section=section;renderExam();saveProgress()}
function startTimer(){if(state.timer)clearInterval(state.timer);state.timer=setInterval(()=>{renderTimers();if(state.deadlineMs&&Date.now()>=state.deadlineMs&&!state.submitted)submitExam(true)},1000);renderTimers()}
function renderTimers(){if(!state.exam){$("#timerStrip").innerHTML="";return}const remaining=state.deadlineMs?Math.max(0,Math.floor((state.deadlineMs-Date.now())/1000)):0;const elapsed=Math.floor((Date.now()-state.startMs)/1000);$("#timerStrip").innerHTML='<span class="pill">'+(state.deadlineMs?'Time left '+fmt(remaining):'Untimed')+'</span><span class="pill">Elapsed '+fmt(elapsed)+'</span>';$("#overallClock").textContent=state.deadlineMs?fmt(remaining):fmt(elapsed);const sectionElapsed=Math.floor((currentSectionMs()[state.section]||0)/1000);const target=state.profile.sectionTargets[state.section]||0;$("#sectionClock").textContent=fmt(sectionElapsed)+(target?' / '+target+'m':'')}
function sectionStatus(){const answered=Object.keys(state.answers).length;const shortDone=state.exam.shortTasks.filter(t=>wordCount(state.writing[t.id])>0).length;const essayDone=wordCount(state.writing.essay)>0?1:0;$("#answeredCount").textContent=answered+" / "+state.exam.mcq.length;$("#writingCount").textContent=(shortDone+essayDone)+" / 3"}
function renderTabs(){const tabs=[["mcq","Part I","MCQ"],["short","Part II","Short"],["essay","Part III","Essay"],["review","Review","Submit"]];$("#sectionTabs").innerHTML=tabs.map(t=>'<button class="tab '+(state.section===t[0]?'active':'')+'" data-section="'+t[0]+'"><small>'+t[1]+'</small>'+t[2]+'</button>').join("");$$(".tab").forEach(btn=>btn.addEventListener("click",()=>switchSection(btn.dataset.section)))}
function renderQuestionMap(){if(state.section!=="mcq"){$("#questionMap").innerHTML="";return}$("#questionMap").innerHTML=state.exam.mcq.map((q,i)=>'<button class="qdot '+(state.answers[q.id]?'answered ':'')+(state.marked[q.id]?'marked ':'')+(i===state.mcqIndex?'active':'')+'" data-index="'+i+'">'+(i+1)+'</button>').join("");$$(".qdot").forEach(btn=>btn.addEventListener("click",()=>{state.mcqIndex=Number(btn.dataset.index);renderExam();saveProgress()}))}
function renderExam(){renderTabs();sectionStatus();renderQuestionMap();renderTimers();if(state.section==="mcq")renderMcq();if(state.section==="short")renderShort();if(state.section==="essay")renderEssay();if(state.section==="review")renderReview()}
function renderDocImages(docs){return docs.map((doc,i)=>'<article class="doc-card"><h3>Document '+(doc.docNumber||i+1)+'</h3><div class="source-line">'+esc(doc.source||doc.set||"Released Regents source")+'</div>'+((doc.stimulusImages||[]).length?doc.stimulusImages.map(img=>'<figure class="stimulus-figure"><img src="'+esc(img.src)+'" alt="'+esc(img.label||"Document stimulus")+'"><figcaption>'+esc(img.label||"Stimulus")+'</figcaption></figure>').join(""):'<p class="source-line">No separate image crop is available for this source.</p>')+'</article>').join("")}
function renderMcq(){const q=state.exam.mcq[state.mcqIndex];$("#sectionKicker").textContent="Part I";$("#sectionTitle").textContent="Multiple Choice "+(state.mcqIndex+1)+" / "+state.exam.mcq.length;$("#workActions").innerHTML='<button class="btn ghost" id="markBtn" type="button">'+(state.marked[q.id]?'Unmark':'Mark For Review')+'</button><button class="btn" id="prevBtn" type="button">Previous</button><button class="btn" id="nextBtn" type="button">Next</button>';const stimulus=(q.stimulusImages||[]).length?q.stimulusImages.map(img=>'<figure class="stimulus-figure"><img src="'+esc(img.src)+'" alt="'+esc(img.label||"Stimulus image")+'"><figcaption>'+esc(img.label||"Original Regents stimulus")+'</figcaption></figure>').join(""):'<div class="stimulus-panel empty">No separate stimulus image for this item.</div>';$("#workArea").innerHTML='<div class="mcq-shell"><aside class="stimulus-panel '+((q.stimulusImages||[]).length?'':'hidden')+'">'+stimulus+'</aside><section class="question-card"><div class="source-line">'+esc(q.course+" · "+q.set+" · "+q.source)+'</div><h3>'+esc(q.stem)+'</h3><div class="choices">'+q.displayedChoices.map(c=>'<button class="choice '+(state.answers[q.id]===c.label?'selected':'')+'" data-choice="'+esc(c.label)+'"><strong>'+esc(c.label)+'.</strong>'+esc(c.text)+'</button>').join("")+'</div></section></div>';$$(".choice").forEach(btn=>btn.addEventListener("click",()=>{state.answers[q.id]=btn.dataset.choice;renderExam();saveProgress()}));$("#markBtn").addEventListener("click",()=>{state.marked[q.id]=!state.marked[q.id];renderExam();saveProgress()});$("#prevBtn").disabled=state.mcqIndex===0;$("#nextBtn").disabled=state.mcqIndex>=state.exam.mcq.length-1;$("#prevBtn").addEventListener("click",()=>{state.mcqIndex=Math.max(0,state.mcqIndex-1);renderExam();saveProgress()});$("#nextBtn").addEventListener("click",()=>{state.mcqIndex=Math.min(state.exam.mcq.length-1,state.mcqIndex+1);renderExam();saveProgress()})}
function renderShort(){$("#sectionKicker").textContent="Part II";$("#sectionTitle").textContent=state.profile.shortTitle;$("#workActions").innerHTML='<button class="btn" type="button" id="toEssayBtn">Go To Essay</button>';$("#workArea").innerHTML='<div class="writing-stack">'+state.exam.shortTasks.map(task=>'<article class="writing-card"><h3>'+esc(task.title)+' <span class="source-line">'+task.points+' pts approx.</span></h3><div class="doc-grid">'+renderDocImages(task.docs)+'</div><ol class="prompt-list">'+task.prompts.map(p=>'<li>'+esc(p)+'</li>').join("")+'</ol><textarea data-writing="'+esc(task.id)+'" placeholder="Write your response here.">'+esc(state.writing[task.id]||"")+'</textarea><div class="word-row"><span id="words-'+esc(task.id)+'">'+wordCount(state.writing[task.id])+' words</span><span>Approximate rubric score appears after submission.</span></div></article>').join("")+'</div>';wireWritingTextareas();$("#toEssayBtn").addEventListener("click",()=>switchSection("essay"))}
function renderEssay(){$("#sectionKicker").textContent="Part III";$("#sectionTitle").textContent=state.profile.essayTitle;$("#workActions").innerHTML='<button class="btn" type="button" id="toReviewBtn">Review Exam</button>';const issueOptions=state.profile.issueTerms.slice(0,8).map(x=>'<span class="pill">'+esc(x)+'</span>').join("");$("#workArea").innerHTML='<div class="writing-stack"><article class="writing-card"><h3>'+esc(state.exam.essay.title)+' <span class="source-line">'+state.exam.essay.points+' pts approx.</span></h3><p class="source-line">'+esc(state.exam.essay.prompt)+'</p><div class="timer-strip">'+issueOptions+'</div><div class="doc-grid">'+renderDocImages(state.exam.essay.docs)+'</div><textarea data-writing="essay" placeholder="Write your essay here.">'+esc(state.writing.essay||"")+'</textarea><div class="word-row"><span id="words-essay">'+wordCount(state.writing.essay)+' words</span><span>Use document evidence, outside information, and clear analysis.</span></div></article></div>';wireWritingTextareas();$("#toReviewBtn").addEventListener("click",()=>switchSection("review"))}
function wireWritingTextareas(){$$("textarea[data-writing]").forEach(area=>{area.addEventListener("input",()=>{state.writing[area.dataset.writing]=area.value;const target=$("#words-"+area.dataset.writing);if(target)target.textContent=wordCount(area.value)+" words";sectionStatus();saveProgress()})})}
function wordCount(v){return String(v||"").trim().split(/\s+/).filter(Boolean).length}
function renderReview(){const unanswered=state.exam.mcq.filter(q=>!state.answers[q.id]).length;const marked=Object.values(state.marked).filter(Boolean).length;const shortDone=state.exam.shortTasks.filter(t=>wordCount(state.writing[t.id])>0).length;const essayDone=wordCount(state.writing.essay)>0;$("#sectionKicker").textContent="Final Check";$("#sectionTitle").textContent="Review And Submit";$("#workActions").innerHTML='<button class="btn primary" id="submitTopBtn" type="button">Submit For Score</button>';$("#workArea").innerHTML='<div class="writing-stack"><div class="feedback-card"><strong>Multiple Choice</strong>'+unanswered+' unanswered · '+marked+' marked for review</div><div class="feedback-card"><strong>Short Answer</strong>'+shortDone+' of '+state.exam.shortTasks.length+' responses started</div><div class="feedback-card"><strong>Long Answer</strong>'+(essayDone?'Essay started':'Essay not started')+'</div><div class="feedback-card"><strong>Approximate scoring</strong>MCQs are answer-keyed. Writing is scored by a practice rubric that checks claim, evidence, analysis, outside information, and organization.</div></div>';$("#submitTopBtn").addEventListener("click",()=>submitExam(false))}
function textHasAny(text,terms){const n=norm(text);return terms.some(t=>n.includes(norm(t)))}
function docHitCount(text,docs){const n=norm(text);let hits=0;docs.forEach((doc,i)=>{const labels=["document "+(i+1),"doc "+(i+1),"source "+(i+1),"document "+(doc.docNumber||i+1),"doc "+(doc.docNumber||i+1)];const byLabel=labels.some(l=>n.includes(l));const byKeyword=(doc.keywords||[]).some(k=>n.includes(k));if(byLabel||byKeyword)hits++});return hits}
function scoreShort(task,text){const wc=wordCount(text);if(!wc)return {score:0,max:task.points,comments:["No response entered."]};const docs=docHitCount(text,task.docs);const analysis=textHasAny(text,["because","therefore","led to","resulted in","caused","effect","impact","similar","different","turning point","changed","shows that","this means"]);const context=textHasAny(text,["during","before","after","historical context","at the time","century","war","revolution","movement","government","empire","constitution"])||textHasAny(text,state.profile.courseTerms);const outside=textHasAny(text,state.profile.courseTerms)&&!textHasAny(text,["document only"]);let score=0;if(context)score++;if(docs>=1)score++;if(analysis)score++;if(task.points===5){if(docs>=2)score++;if(outside||wc>=140)score++}score=Math.min(task.points,score);const comments=[];if(!context)comments.push("Add clearer historical context before using the documents.");if(docs<task.docs.length)comments.push("Use evidence from both documents, not just one.");if(!analysis)comments.push("Explain the relationship with cause/effect, similarity/difference, or impact language.");if(task.points===5&&!outside)comments.push("Add one outside U.S. History detail beyond the documents.");if(!comments.length)comments.push("This response has the core evidence and explanation expected for practice.");return {score,max:task.points,comments}}
function scoreEssay(text,docs){const wc=wordCount(text);if(!wc)return {score:0,max:state.profile.essayMax,comments:["No essay entered."],docHits:0};const docHits=docHitCount(text,docs);const hasClaim=textHasAny(text,state.profile.issueTerms)||textHasAny(text,["issue","constitutional","civic","enduring","problem","challenge","conflict","rights","power"]);const analysis=textHasAny(text,["because","therefore","as a result","led to","impact","changed","continued","endured","persisted","caused","significant","shows that"]);const outside=textHasAny(text,state.profile.courseTerms);const organized=(String(text).split(/\n\s*\n/).filter(p=>p.trim()).length>=2)||wc>=320;let score=0;if(hasClaim)score++;if(docHits>=2)score++;if(analysis)score++;if(outside)score++;if(organized&&docHits>=3)score++;const comments=[];if(!hasClaim)comments.push("State the enduring issue or civic issue directly in the first few sentences.");if(docHits<3)comments.push("Use evidence from at least three of the five essay documents by name or by specific detail.");if(!analysis)comments.push("After each piece of evidence, explain why it proves the issue or impact.");if(!outside)comments.push("Add outside information from the course to lift the essay above summary.");if(!organized)comments.push("Use clear paragraphs: claim, document evidence, outside information, and conclusion.");if(!comments.length)comments.push("This essay shows the basic shape of a high-scoring practice response.");return {score:Math.min(state.profile.essayMax,score),max:state.profile.essayMax,comments,docHits}}
function gradeExam(){const mcqCorrect=state.exam.mcq.filter(q=>state.answers[q.id]===q.correct).length;const missed=state.exam.mcq.filter(q=>state.answers[q.id]!==q.correct);const shortScores=state.exam.shortTasks.map(t=>scoreShort(t,state.writing[t.id]||""));const essayScore=scoreEssay(state.writing.essay||"",state.exam.essay.docs);const shortTotal=shortScores.reduce((s,r)=>s+r.score,0);const raw=mcqCorrect+shortTotal+essayScore.score;const rawMax=28+state.profile.shortMax+state.profile.essayMax;const percent=Math.round(raw/rawMax*100);return {mcqCorrect,missed,shortScores,essayScore,shortTotal,raw,rawMax,percent}}
function topMissedSets(missed){const counts={};missed.forEach(q=>{counts[q.set]=(counts[q.set]||0)+1;(q.tags||[]).slice(0,3).forEach(t=>counts[t]=(counts[t]||0)+1)});return Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5)}
function coachComments(result){const comments=[];const mcqPct=Math.round(result.mcqCorrect/28*100);comments.push(["MCQ accuracy",mcqPct+"% on the 28-question section. "+(mcqPct>=80?"Keep doing mixed timed sets so source reading stays sharp.":mcqPct>=65?"You are close; the fastest gain is reviewing missed source questions by topic.":"This needs daily mixed MCQ practice with stimulus annotation before answer choice elimination.")]);const stimMiss=result.missed.filter(sourceBased).length;const directMiss=result.missed.length-stimMiss;if(stimMiss>=directMiss&&stimMiss>0)comments.push(["Stimulus reading","Most missed MCQs were source-based. Read the title, date, speaker, and visual labels before looking at the choices."]);else if(directMiss>0)comments.push(["Content recall","Several misses were direct content questions. Build a one-page hit list of the names, laws, events, and concepts that appear in the missed set."]);result.shortScores.forEach((s,i)=>comments.push([state.exam.shortTasks[i].title,s.score+"/"+s.max+" approx. "+s.comments[0]]));comments.push([state.profile.essayTitle,result.essayScore.score+"/"+result.essayScore.max+" approx. "+result.essayScore.comments[0]]);return comments}
function submitExam(expired){if(state.submitted)return;if(!expired){const unanswered=state.exam.mcq.filter(q=>!state.answers[q.id]).length;if(unanswered&&!confirm("You still have "+unanswered+" unanswered multiple-choice questions. Submit anyway?"))return}state.sectionMs=currentSectionMs();state.submitted=true;if(state.timer)clearInterval(state.timer);const result=gradeExam();state.result=result;clearSaved();window.MrMacsAnalytics?.track("game_complete",{gameId:"regents-practice-exam",title:state.profile.title,score:result.percent,accuracy:Math.round(result.mcqCorrect/28*100),questions:28},{counter:"game-completions"});renderResults(expired)}
function renderResults(expired){const r=state.result;show("resultsScreen");$("#timerStrip").innerHTML='<span class="pill">Practice complete</span>';$("#resultTitle").textContent=state.profile.label+" Score Report";$("#resultMetrics").innerHTML=[[r.percent+"%","approximate practice score"],[r.raw+"/"+r.rawMax,"raw points"],[r.mcqCorrect+"/28","MCQ"],[(r.shortTotal+r.essayScore.score)+"/"+(state.profile.shortMax+state.profile.essayMax),"writing"]].map(m=>'<div class="metric"><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></div>').join("");const comments=coachComments(r);if(expired)comments.unshift(["Timer","The exam submitted when time expired. Practice pacing by moving on from stuck MCQs after about two minutes."]);$("#coachComments").innerHTML=comments.map(c=>'<div class="feedback-card"><strong>'+esc(c[0])+'</strong>'+esc(c[1])+'</div>').join("");const targets=topMissedSets(r.missed);$("#studyTargets").innerHTML=(targets.length?targets.map(t=>'<div class="feedback-card"><strong>'+esc(t[0])+'</strong>'+t[1]+' missed or weak signal</div>'):[["No major MCQ target","Use a harder mixed bank next."]].map(t=>'<div class="feedback-card"><strong>'+esc(t[0])+'</strong>'+esc(t[1])+'</div>')).join("");$("#reviewList").innerHTML=state.exam.mcq.map((q,i)=>{const chosen=state.answers[q.id];const ok=chosen===q.correct;const right=q.displayedChoices.find(c=>c.label===q.correct);const picked=q.displayedChoices.find(c=>c.label===chosen);return '<div class="review-item '+(ok?'correct':'missed')+'"><strong>Question '+(i+1)+' · '+(ok?'Correct':'Missed')+'</strong><br>'+esc(q.stem)+'<br><span class="source-line">'+esc(q.source+" · "+q.set)+'</span><br>Your answer: '+esc(chosen?(chosen+". "+(picked?.text||"")):"blank")+'<br>Correct: '+esc(q.correct+". "+(right?.text||""))+'<br>'+esc(q.explanation||"Review this source and topic.")+'</div>'}).join("")}
function reviewWriting(){show("examScreen");state.submitted=false;switchSection("short");state.submitted=true}

fetch("../../data/regents-gauntlet-bank.json?v=20260428-exam1").then(r=>r.json()).then(bank=>{state.bank=bank;renderSetup()});
$("#courseSelect").addEventListener("change",renderPreview);
$("#timerSelect").addEventListener("change",renderPreview);
$("#startBtn").addEventListener("click",startExam);
$("#resumeBtn").addEventListener("click",resumeExam);
$("#submitBtn").addEventListener("click",()=>submitExam(false));
$("#newExamBtn").addEventListener("click",()=>{if(state.timer)clearInterval(state.timer);state.exam=null;state.submitted=false;$("#timerStrip").innerHTML="";show("setupScreen");renderSetup()});
$("#reviewWritingBtn").addEventListener("click",reviewWriting);
