const CONFIG={"id":"vocab-vault","title":"Vocab Vault","subtitle":"Type the term from real review clues. Built for vocabulary, people, laws, cases, and concepts.","mode":"vocab","bank":"chrono","gameType":"Typing Drill","categories":["Vocabulary","Typing","Self Check","Course Select"],"accent":"#74f0aa","glyph":"ABC","timeLimit":0};
const state={bank:null,questions:[],pool:[],current:null,score:0,streak:0,answered:0,missed:0,start:0,deadline:0,timer:null,locked:false};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const SourceBank=typeof window!=="undefined"?window.MrMacsSourceBank:null;
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const norm=v=>String(v||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
function shuffle(a){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function uniq(values){return[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}))}
function show(id){$$(".screen").forEach(s=>s.classList.remove("active"));$("#"+id).classList.add("active");scrollTo({top:0,behavior:"auto"})}
function fmt(sec){sec=Math.max(0,Math.floor(sec));return Math.floor(sec/60)+":"+String(sec%60).padStart(2,"0")}
function bankUrl(){return CONFIG.bank==="regents"?"../../data/regents-gauntlet-bank.json":"../../data/chrono-defense-bank.json"}
function rawQuestions(){return CONFIG.bank==="regents"?(state.bank.questions||[]):((state.bank.questions||[]).filter(q=>q.answer||q.choices))}
function sourceBased(q){return (q.stimulusImages&&q.stimulusImages.length)||q.stimulusRequired||/based on|according to|document|map|cartoon|graph|chart|excerpt|passage|photograph|source/i.test(q.stem||q.prompt||"")}
function playablePrompt(q){return SourceBank?SourceBank.playableSharedPrompt(q):!!String(q.prompt||q.stem||"").trim()}
function promptText(q){return SourceBank?.displayPrompt?SourceBank.displayPrompt(q):String(q.prompt||q.stem||"").trim()}
function sourceText(q){return SourceBank?.displaySource?SourceBank.displaySource(q):String(q.source||q.category||"").trim()}
function stimulusLabel(q,img){return SourceBank?.displayStimulusLabel?SourceBank.displayStimulusLabel(q,img):String(img?.label||q.source||"Source").trim()}
function hydrate(){state.questions=rawQuestions().filter(q=>playablePrompt(q)&&(CONFIG.mode!=="source"||sourceBased(q)));const courses=uniq(state.questions.map(q=>q.course));$("#courseSelect").innerHTML=["All Courses",...courses].map(c=>'<option>'+esc(c)+'</option>').join("");updateSets();$("#courseSelect").addEventListener("change",updateSets);$("#bankMetrics").innerHTML=[[state.questions.length,"review clues"],[courses.length,"courses"],[CONFIG.timeLimit?fmt(CONFIG.timeLimit):"open","timer"]].map(m=>'<div class="metric"><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></div>').join("");$("#modeNotes").innerHTML=CONFIG.mode==="vocab"?'<p>Type the answer. Only clear, one-answer review clues appear here, and listed aliases count.</p>':CONFIG.mode==="source"?'<p>Only source-based Regents questions appear. Read the image, title, caption, date, and speaker before answering.</p>':'<p>Questions come from the full review library. Only clean, one-answer prompts appear, with nearby terms used as distractors.</p>';topStats()}
function updateSets(){const course=$("#courseSelect").value;const qs=state.questions.filter(q=>course==="All Courses"||q.course===course);const sets=uniq(qs.map(q=>q.set||q.day||q.subject));$("#setSelect").innerHTML=["All Sets",...sets].map(s=>'<option>'+esc(s)+'</option>').join("")}
function filtered(){const course=$("#courseSelect").value;const set=$("#setSelect").value;return state.questions.filter(q=>(course==="All Courses"||q.course===course)&&(set==="All Sets"||(q.set||q.day||q.subject)===set))}
function makeMcq(q){if(q.choices&&q.choices.length){const correct=(q.choices||[]).find(c=>String(c.label)===String(q.correct));return {kind:"mcq",prompt:promptText(q),choices:shuffle(q.choices.map(c=>({text:c.text,correct:String(c.label)===String(q.correct)}))),answer:correct?.text||"",explanation:q.explanation||"",course:q.course,set:q.set||q.day,source:sourceText(q),images:q.stimulusImages||[]}}const same=state.questions.filter(x=>x.course===q.course&&x.answer&&x.answer!==q.answer);const distractors=shuffle(same).slice(0,3).map(x=>x.answer);return {kind:"mcq",prompt:promptText(q),choices:shuffle([q.answer,...distractors]).map(text=>({text,correct:text===q.answer})),answer:q.answer,explanation:q.explanation||"",course:q.course,set:q.set||q.day,source:sourceText(q),images:[]}}
function makeVocab(q){return {kind:"vocab",prompt:promptText(q),answer:q.answer||((q.choices||[]).find(c=>String(c.label)===String(q.correct))?.text||""),aliases:q.aliases||[],explanation:q.explanation||"",course:q.course,set:q.set||q.day,source:sourceText(q),images:q.stimulusImages||[]}}
function nextQuestion(){state.locked=false;if(!state.pool.length)state.pool=shuffle(filtered());if(!state.pool.length){finish();return}const raw=state.pool.pop();state.current=CONFIG.mode==="vocab"?makeVocab(raw):makeMcq(raw);renderQuestion()}
function renderStimulus(q){$("#stimulus").innerHTML=q.images?.length?'<div class="stimulus-grid">'+q.images.map(img=>'<figure><img src="'+esc(img.src)+'" alt="'+esc(stimulusLabel(q,img)||"Stimulus")+'"><figcaption class="source-line">'+esc(stimulusLabel(q,img)||q.source||"Source")+'</figcaption></figure>').join("")+'</div>':""}
function renderQuestion(){const q=state.current;$("#questionMeta").textContent=[q.course,q.set,q.source].filter(Boolean).join(" · ");$("#prompt").textContent=q.prompt;$("#feedback").textContent="";renderStimulus(q);if(q.kind==="vocab"){$("#answerArea").innerHTML='<div class="type-row"><input id="answerInput" autocomplete="off" placeholder="Type the answer"><button class="btn primary" id="checkBtn" type="button">Check</button><button class="btn ghost" id="revealBtn" type="button">Reveal</button></div>';$("#answerInput").focus();$("#checkBtn").onclick=checkTyped;$("#revealBtn").onclick=()=>grade(false,true);$("#answerInput").addEventListener("keydown",e=>{if(e.key==="Enter")checkTyped()})}else{$("#answerArea").innerHTML='<div class="choice-grid">'+q.choices.map((c,i)=>'<button class="choice" data-index="'+i+'"><strong>'+String.fromCharCode(65+i)+'.</strong> '+esc(c.text)+'</button>').join("")+'</div>';$$(".choice").forEach(btn=>btn.onclick=()=>grade(q.choices[Number(btn.dataset.index)].correct,false,btn))}}
function checkTyped(){const q=state.current;const value=norm($("#answerInput").value);const ok=[q.answer,...(q.aliases||[])].some(a=>norm(a)===value||value&&norm(a).includes(value)&&value.length>=5);grade(ok,false)}
function grade(ok,revealed,button){if(state.locked)return;state.locked=true;state.answered++;if(ok){state.streak++;state.score+=10+Math.min(30,state.streak*2)}else{state.streak=0;state.missed++}if(button){button.classList.add(ok?"correct":"wrong");$$(".choice").forEach((b,i)=>{if(state.current.choices[i].correct)b.classList.add("correct")})}$("#feedback").innerHTML='<strong>'+esc(ok?"Correct":revealed?"Revealed":"Not yet")+'</strong><br>Answer: '+esc(state.current.answer)+'<br>'+esc(state.current.explanation||"Review this item and try another one.");topStats();setTimeout(nextQuestion,ok?850:1500)}
function topStats(){const left=state.deadline?Math.max(0,Math.floor((state.deadline-Date.now())/1000)):0;$("#score").textContent=state.score;$("#streak").textContent=state.streak;$("#answered").textContent=state.answered;$("#clock").textContent=state.deadline?fmt(left):"--";$("#topStats").innerHTML=[state.score+" pts",state.streak+" streak",state.answered+" answered"].map(x=>'<span>'+esc(x)+'</span>').join("")}
function start(){state.pool=shuffle(filtered());state.score=0;state.streak=0;state.answered=0;state.missed=0;state.start=Date.now();state.deadline=CONFIG.timeLimit?Date.now()+CONFIG.timeLimit*1000:0;if(state.timer)clearInterval(state.timer);state.timer=setInterval(()=>{topStats();if(state.deadline&&Date.now()>=state.deadline)finish()},500);show("play");nextQuestion()}
function finish(){if(state.timer)clearInterval(state.timer);show("results");const pct=state.answered?Math.round((state.answered-state.missed)/state.answered*100):0;$("#resultTitle").textContent=CONFIG.title+" Results";$("#resultMetrics").innerHTML=[[state.score,"points"],[state.answered,"answered"],[pct+"%","accuracy"]].map(m=>'<div class="metric"><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></div>').join("");$("#coach").innerHTML=pct>=85?"Strong run. Move to a harder course set or a full exam.":pct>=65?"Good base. Replay the same course and slow down on misses.":"Use this as a warm-up: read the explanation, then replay with one course selected.";window.MrMacsAnalytics?.track("game_complete",{gameId:CONFIG.id,title:CONFIG.title,score:pct,questions:state.answered},{counter:"game-completions"})}
fetch(bankUrl()).then(r=>r.json()).then(data=>{state.bank=data;hydrate()});
$("#startBtn").onclick=start;$("#skipBtn").onclick=nextQuestion;$("#finishBtn").onclick=finish;$("#againBtn").onclick=()=>{show("setup");hydrate()};
