import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.164.1/build/three.module.js";

const state={bank:null,course:"All Courses",set:"All Sets",length:8,assist:true,phase:"setup",scene:null,camera:null,renderer:null,ship:null,clock:null,ready:false,run:null,beacon:null,storm:null,clouds:[],stars:null,gates:[],keys:{},pointer:null,audio:null};
const $=s=>document.querySelector(s);
const $$=s=>Array.from(document.querySelectorAll(s));
function uniq(a){return Array.from(new Set(a.filter(Boolean))).sort((x,y)=>x.localeCompare(y,undefined,{numeric:true}))}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function shuffle(a){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function audio(){try{state.audio=state.audio||new (window.AudioContext||window.webkitAudioContext)();return state.audio}catch(e){return null}}
function tone(kind){try{const c=audio();if(!c)return;const o=c.createOscillator(),g=c.createGain(),now=c.currentTime;const m={launch:[120,360,.28,"triangle"],scan:[440,620,.11,"sine"],good:[560,1040,.16,"sine"],bad:[180,90,.22,"sawtooth"],hit:[120,70,.12,"square"],ring:[520,760,.055,"sine"]}[kind]||[500,760,.1,"sine"];o.type=m[3];o.frequency.setValueAtTime(m[0],now);o.frequency.exponentialRampToValueAtTime(m[1],now+m[2]);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(kind==="bad"?.052:kind==="ring"?.014:.03,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+m[2]);o.connect(g);g.connect(c.destination);o.start();o.stop(now+m[2]+.03)}catch(e){}}
function engine(on){try{const c=audio();if(!c)return;if(on&&state.engine)return;if(!on&&state.engine){const now=c.currentTime;state.engine.gain.gain.exponentialRampToValueAtTime(.0001,now+.18);state.engine.osc.stop(now+.22);state.engine=null;return}if(on){const osc=c.createOscillator(),gain=c.createGain(),filter=c.createBiquadFilter();osc.type="sawtooth";osc.frequency.value=62;filter.type="lowpass";filter.frequency.value=170;gain.gain.value=.0001;osc.connect(filter);filter.connect(gain);gain.connect(c.destination);osc.start();gain.gain.exponentialRampToValueAtTime(.016,c.currentTime+.35);state.engine={osc,gain,filter}}}catch(e){}}
function sourceBased(q){return q.stimulusRequired||/based on|article|passage|excerpt|map|graph|chart|cartoon|headline|timeline|photograph|image|source|document|letter|speech|poem|newspaper/i.test(q.stem)}
function questions(){return state.bank.questions.filter(q=>(state.course==="All Courses"||q.course===state.course)&&(state.set==="All Sets"||q.set===state.set))}
function balancedPick(items,count){const groups=new Map();shuffle(items).forEach(q=>{const key=q.set||q.course;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(q)});const picked=[];while(picked.length<count&&Array.from(groups.values()).some(g=>g.length)){for(const group of groups.values()){if(group.length&&picked.length<count)picked.push(group.pop())}}return picked}
function renderSetup(){const qs=state.bank.questions;$("#stats").innerHTML=[[qs.length,"question bank"],[qs.filter(sourceBased).length,"source missions"],[uniq(qs.map(q=>q.set)).length,"review sets"]].map(m=>'<div class="stat"><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></div>').join("");$("#courseSelect").innerHTML=["All Courses"].concat(uniq(qs.map(q=>q.course))).map(c=>'<option>'+esc(c)+'</option>').join("");renderSets();renderPreview()}
function renderSets(){const sets=uniq(state.bank.questions.filter(q=>state.course==="All Courses"||q.course===state.course).map(q=>q.set));$("#setSelect").innerHTML=["All Sets"].concat(sets).map(s=>'<option>'+esc(s)+'</option>').join("");if(!["All Sets"].concat(sets).includes(state.set))state.set="All Sets";$("#setSelect").value=state.set}
function missionPool(){const pool=questions();const sourced=pool.filter(q=>sourceBased(q)&&(q.stimulusImages||[]).length);return sourced.length?sourced:pool}
function renderPreview(){const pool=missionPool();$("#preview").innerHTML='<strong>'+Math.min(state.length,pool.length)+' archive beacons queued</strong><br>'+pool.length+' source-ready mission questions from '+esc(state.course)+' · '+esc(state.set)+'.<br>Questions are not shown during flight. Source-based missions open the source scan first.'}
function init3d(){if(state.ready)return;const canvas=$("#stage");state.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:"high-performance"});state.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.35));state.renderer.setSize(innerWidth,innerHeight);state.scene=new THREE.Scene();state.scene.fog=new THREE.FogExp2(0x7dbced,.011);state.camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.1,900);state.camera.position.set(0,4.2,13);state.clock=new THREE.Clock();
  const loader=new THREE.TextureLoader();const skyTex=loader.load("../../assets/time-pilot-sky.png");skyTex.colorSpace=THREE.SRGBColorSpace;const sky=new THREE.Mesh(new THREE.SphereGeometry(420,40,24),new THREE.MeshBasicMaterial({map:skyTex,side:THREE.BackSide,transparent:true,opacity:.58,depthWrite:false}));sky.rotation.y=.8;state.scene.add(sky);
  const worldTex=loader.load("../../assets/time-pilot-hero.png");worldTex.colorSpace=THREE.SRGBColorSpace;const world=new THREE.Mesh(new THREE.PlaneGeometry(310,174),new THREE.MeshBasicMaterial({map:worldTex,transparent:true,opacity:.82,depthWrite:false}));world.position.set(0,14,-260);state.scene.add(world);
  state.scene.add(new THREE.HemisphereLight(0xbbe9ff,0x15234a,1.5));const sun=new THREE.DirectionalLight(0xffe2aa,2.2);sun.position.set(-18,22,12);state.scene.add(sun);const rim=new THREE.PointLight(0x58eaff,2.2,80);rim.position.set(0,8,-20);state.scene.add(rim);
  makeTerrain();makeClouds();makeStars();state.ship=makeShip();state.scene.add(state.ship);state.ready=true;addEventListener("resize",resize);loop()}
function makeTerrain(){const mat=new THREE.MeshStandardMaterial({color:0x1b6f72,roughness:.82,metalness:.05,transparent:true,opacity:.88});for(let i=0;i<42;i++){const geo=new THREE.ConeGeometry(6+Math.random()*18,1+Math.random()*4,7);const m=new THREE.Mesh(geo,mat);m.position.set((Math.random()-.5)*150,-8-Math.random()*3,-Math.random()*520-22);m.rotation.y=Math.random()*Math.PI;state.scene.add(m)}const sea=new THREE.Mesh(new THREE.PlaneGeometry(520,900,20,20),new THREE.MeshStandardMaterial({color:0x0b5f85,roughness:.28,metalness:.35,transparent:true,opacity:.52}));sea.rotation.x=-Math.PI/2;sea.position.y=-9;sea.position.z=-230;state.scene.add(sea)}
function makeClouds(){const mat=new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.34,depthWrite:false});for(let i=0;i<44;i++){const c=new THREE.Mesh(new THREE.SphereGeometry(2+Math.random()*6,12,8),mat);c.scale.set(1.8+Math.random()*3,.35+Math.random()*.35,.6+Math.random()*1.4);c.position.set((Math.random()-.5)*140,4+Math.random()*30,-Math.random()*520-20);state.scene.add(c);state.clouds.push(c)}}
function makeStars(){const geo=new THREE.BufferGeometry(),pts=[];for(let i=0;i<360;i++)pts.push((Math.random()-.5)*180,Math.random()*80-8,-Math.random()*520);geo.setAttribute("position",new THREE.Float32BufferAttribute(pts,3));state.stars=new THREE.Points(geo,new THREE.PointsMaterial({color:0xdffcff,size:.09,transparent:true,opacity:.7}));state.scene.add(state.stars)}
function makeShip(){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.ConeGeometry(.72,2.7,5),new THREE.MeshStandardMaterial({color:0xf5fbff,metalness:.7,roughness:.22,emissive:0x102a34}));body.rotation.x=Math.PI/2;const wingMat=new THREE.MeshStandardMaterial({color:0x1a2130,metalness:.75,roughness:.18,emissive:0x02070e});const wing=new THREE.Mesh(new THREE.BoxGeometry(4.2,.12,.72),wingMat);wing.position.z=.15;const core=new THREE.Mesh(new THREE.SphereGeometry(.35,20,14),new THREE.MeshBasicMaterial({color:0x58eaff}));core.position.z=1.15;const trail=new THREE.Mesh(new THREE.ConeGeometry(.32,3,18),new THREE.MeshBasicMaterial({color:0x58eaff,transparent:true,opacity:.48}));trail.rotation.x=-Math.PI/2;trail.position.z=2.5;g.add(body,wing,core,trail);g.position.set(0,-.55,3.3);return g}
function resize(){state.camera.aspect=innerWidth/innerHeight;state.camera.updateProjectionMatrix();state.renderer.setSize(innerWidth,innerHeight)}
function clearObject(obj){if(!obj)return;if(obj.group)state.scene.remove(obj.group);else state.scene.remove(obj)}
function makeBeacon(){clearObject(state.beacon);const group=new THREE.Group();const gold=new THREE.MeshBasicMaterial({color:0xffd76d,transparent:true,opacity:.96});const cyan=new THREE.MeshBasicMaterial({color:0x58eaff,transparent:true,opacity:.56});const ring=new THREE.Mesh(new THREE.TorusGeometry(4.6,.16,16,88),gold);const inner=new THREE.Mesh(new THREE.TorusGeometry(2.55,.06,12,64),cyan);const core=new THREE.Mesh(new THREE.IcosahedronGeometry(.62,2),new THREE.MeshBasicMaterial({color:0xfff1b2,transparent:true,opacity:.9}));ring.rotation.x=Math.PI/2;inner.rotation.x=Math.PI/2;group.add(ring,inner,core);const light=new THREE.PointLight(0xffd76d,1.4,28);group.add(light);group.position.set((Math.random()-.5)*13,Math.random()*4.8-.8,-255);state.scene.add(group);state.beacon={group,hit:false}}
function makeStorm(){clearObject(state.storm);const group=new THREE.Group();const core=new THREE.Mesh(new THREE.IcosahedronGeometry(2.2,2),new THREE.MeshStandardMaterial({color:0xff526d,emissive:0x3f0310,roughness:.45,transparent:true,opacity:.86}));const ring=new THREE.Mesh(new THREE.TorusGeometry(3,.08,12,48),new THREE.MeshBasicMaterial({color:0xff526d,transparent:true,opacity:.5}));ring.rotation.x=Math.PI/2;group.add(core,ring);group.position.set((Math.random()-.5)*18,Math.random()*8-2,-185-Math.random()*100);state.scene.add(group);state.storm={group,hit:false}}
function clearWaypoints(){for(const w of state.waypoints||[])state.scene.remove(w.group);state.waypoints=[]}
function makeWaypoints(){clearWaypoints();const mat=new THREE.MeshBasicMaterial({color:0x58eaff,transparent:true,opacity:.34});for(let i=0;i<9;i++){const group=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(3.2,.045,10,48),mat);ring.rotation.x=Math.PI/2;group.add(ring);group.position.set((Math.random()-.5)*15,Math.random()*7-2,-55-i*24);state.scene.add(group);state.waypoints.push({group,hit:false})}}
function updateWaypoints(dt){const r=state.run;if(!r)return;for(const w of state.waypoints){w.group.position.z+=dt*24;w.group.rotation.z+=dt*.45;if(!w.hit&&w.group.position.z>-4&&w.group.position.z<8){const d=w.group.position.distanceTo(new THREE.Vector3(r.x,r.y,0));if(d<3.6){w.hit=true;r.combo=Math.min(9,(r.combo||0)+1);r.score+=50*r.combo;tone("ring")}}if(w.group.position.z>22){w.hit=false;w.group.position.set((Math.random()-.5)*15,Math.random()*7-2,-230-Math.random()*50)}}}
function currentQuestion(){return state.run.questions[state.run.index]}
function start(){init3d();const pool=missionPool();state.run={questions:balancedPick(pool,Math.min(state.length,pool.length)),index:0,score:0,hull:100,beacons:0,correct:0,missed:[],x:0,y:0,vx:0,vy:0,targetX:0,targetY:0,scanSeen:false,beaconDelay:2.2,flightClock:0,minFlight:9,checkpointReadyAt:performance.now()+10500,combo:0};state.phase="flight";hidePanels();$("#hud").classList.remove("hidden");$("#touchControls").classList.remove("hidden");$("#beaconText").textContent="0 / "+state.run.questions.length;makeBeacon();makeStorm();makeWaypoints();engine(true);tone("launch");}
function hidePanels(){$$("#setup,#archivePanel,#answerPanel,#feedbackPanel,#pausePanel,#summary").forEach(el=>el.classList.add("hidden"))}
function updateHud(){if(!state.run)return;$("#scoreText").textContent=state.run.score;$("#beaconText").textContent=state.run.beacons+" / "+state.run.questions.length;$("#hullText").textContent=Math.max(0,Math.round(state.run.hull))+"%"}
function loop(){requestAnimationFrame(loop);if(!state.ready)return;const dt=Math.min(.033,state.clock.getDelta());if(state.phase==="flight")updateFlight(dt);if(state.phase==="answer")updateAnswer(dt);animateWorld(dt);state.renderer.render(state.scene,state.camera)}
function animateWorld(dt){for(const c of state.clouds){c.position.z+=dt*14;if(c.position.z>18)c.position.z=-520}if(state.stars)state.stars.rotation.y+=dt*.008;state.ship.rotation.z=-(state.run?.x||0)*.08;state.ship.rotation.x=(state.run?.y||0)*.035}
function controlVector(){let ax=0,ay=0;if(state.keys.ArrowLeft||state.keys.a)ax-=1;if(state.keys.ArrowRight||state.keys.d)ax+=1;if(state.keys.ArrowUp||state.keys.w)ay+=1;if(state.keys.ArrowDown||state.keys.s)ay-=1;if(state.pointer){ax+=(state.pointer.x-.5)*2;ay+=-(state.pointer.y-.5)*1.5}return {ax,ay}}
function updateFlight(dt){const r=state.run,cv=controlVector(),assist=state.assist?0.55:0;r.flightClock=(r.flightClock||0)+dt;r.vx+=(cv.ax*24-r.vx*4)*dt;r.vy+=(cv.ay*18-r.vy*4)*dt;r.x=THREE.MathUtils.clamp(r.x+r.vx*dt,-8.5,8.5);r.y=THREE.MathUtils.clamp(r.y+r.vy*dt,-4.5,6.5);if(assist){r.x+=(-r.x)*assist*dt*.18;r.y+=(-r.y)*assist*dt*.14}state.ship.position.x+=(r.x-state.ship.position.x)*Math.min(1,dt*9);state.ship.position.y+=((r.y-.55)-state.ship.position.y)*Math.min(1,dt*9);$("#modeText").textContent="Flight Mode";$("#missionText").textContent="Thread the blue approach rings. Lock the gold archive beacon to open the source checkpoint.";updateWaypoints(dt);
  r.beaconDelay=Math.max(0,(r.beaconDelay||0)-dt);if(r.beaconDelay>0){$("#missionText").textContent="Launch corridor: build speed through the blue rings. Archive lock in "+Math.ceil(r.beaconDelay)+".";updateHud();return}
  if(state.beacon){state.beacon.group.position.z+=dt*20;state.beacon.group.rotation.z+=dt*.8;const lockTime=Math.max(0,(r.checkpointReadyAt-performance.now())/1000);const distance=Math.max(0,Math.round((Math.abs(state.beacon.group.position.z)+5)*6));$("#missionText").textContent=lockTime>0?"Approach run: hit blue rings. Archive lock in "+Math.ceil(lockTime)+"s.":"Archive beacon ahead: "+distance+" m. Fly through the gold ring to trigger the source scan.";const d=state.beacon.group.position.distanceTo(new THREE.Vector3(r.x,r.y,-1));if(!state.beacon.hit&&lockTime<=0&&r.flightClock>r.minFlight&&state.beacon.group.position.z>-5&&d<5.4){state.beacon.hit=true;r.score+=650+(r.combo||0)*80;r.beacons++;updateHud();triggerArchive() }else if(state.beacon.group.position.z>16&&!state.beacon.hit){r.hull-=lockTime>0?0:8;r.combo=0;r.flightClock=0;r.beaconDelay=1.2;if(lockTime>0)r.checkpointReadyAt=performance.now()+2600;makeBeacon();updateHud()}}
  if(state.storm){state.storm.group.position.z+=dt*20;state.storm.group.rotation.x+=dt*.8;state.storm.group.rotation.y+=dt*1.1;const d=state.storm.group.position.distanceTo(new THREE.Vector3(r.x,r.y,0));if(!state.storm.hit&&state.storm.group.position.z>-4&&d<3.8){state.storm.hit=true;r.hull-=18;tone("hit");makeStorm();updateHud();if(r.hull<=0)finish()}else if(state.storm.group.position.z>18)makeStorm()}
  updateHud()}
function triggerArchive(){state.phase="archive";engine(false);clearObject(state.beacon);state.beacon=null;clearObject(state.storm);state.storm=null;clearWaypoints();const q=currentQuestion();$("#hud").classList.add("hidden");$("#touchControls").classList.add("hidden");$("#archivePanel").classList.remove("hidden");$("#archiveTitle").textContent=sourceBased(q)?"Source Scan Required":"Archive Beacon";$("#archivePrompt").textContent=sourceBased(q)?"Study the source page first. Then open the answer gates and fly through the best answer.":"This is a content beacon. Open the answer gates when ready.";const imgs=(q.stimulusImages||[]);$("#sourcePages").innerHTML=sourceBased(q)&&imgs.length?imgs.map((img,i)=>'<figure><img src="'+esc(img.src)+'" alt="'+esc(img.label||("Source page "+(i+1)))+'"><figcaption>'+esc(img.label||("Source page "+(i+1)))+'</figcaption></figure>').join(""):'<div class="preview"><strong>No separate stimulus needed.</strong><br>This checkpoint is direct content recall from '+esc(q.set)+'.</div>';tone("scan")}
function openGates(){const q=currentQuestion();$("#archivePanel").classList.add("hidden");$("#hud").classList.remove("hidden");$("#touchControls").classList.remove("hidden");$("#answerPanel").classList.remove("hidden");$("#questionMeta").textContent=q.course+" · "+q.day+" · Archive "+(state.run.index+1)+"/"+state.run.questions.length;$("#questionText").textContent=q.stem;$("#answerChoices").innerHTML=q.choices.map((c,i)=>'<button class="answer" type="button" data-index="'+i+'"><b>Gate '+(i+1)+' · '+esc(c.label)+'</b><span>'+esc(c.text)+'</span></button>').join("");$$(".answer").forEach(btn=>btn.addEventListener("click",()=>chooseGate(Number(btn.dataset.index))));state.gates=makeGates(q);state.run.answerDelay=5.5;state.phase="answer";engine(true)}
function makeGates(q){for(const g of state.gates)state.scene.remove(g.group);const xs=[-9,-3,3,9];return q.choices.map((c,i)=>{const group=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(2.25,.14,16,68),new THREE.MeshBasicMaterial({color:0x58eaff,transparent:true,opacity:.9}));const inner=new THREE.Mesh(new THREE.TorusGeometry(1.5,.05,12,48),new THREE.MeshBasicMaterial({color:0xffd76d,transparent:true,opacity:.54}));ring.rotation.x=Math.PI/2;inner.rotation.x=Math.PI/2;const label=new THREE.Sprite(new THREE.SpriteMaterial({map:textTexture(c.label),transparent:true}));label.position.y=2.7;label.scale.set(3.2,1.1,1);group.add(ring,inner,label);group.position.set(xs[i],0,-130);group.userData={i,label:c.label};state.scene.add(group);return {group,i,label:c.label,hit:false}})}
function textTexture(text){const c=document.createElement("canvas");c.width=512;c.height=192;const ctx=c.getContext("2d");ctx.fillStyle="rgba(5,10,22,.86)";ctx.strokeStyle="rgba(255,215,109,.85)";ctx.lineWidth=8;ctx.roundRect(10,10,492,172,24);ctx.fill();ctx.stroke();ctx.fillStyle="#f7fbff";ctx.font="900 70px system-ui, sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("Gate "+text,256,96);return new THREE.CanvasTexture(c)}
function updateAnswer(dt){const r=state.run,cv=controlVector();r.vx+=(cv.ax*22-r.vx*4)*dt;r.vy+=(cv.ay*16-r.vy*4)*dt;r.x=THREE.MathUtils.clamp(r.x+r.vx*dt,-10,10);r.y=THREE.MathUtils.clamp(r.y+r.vy*dt,-4.2,5.2);state.ship.position.x+=(r.x-state.ship.position.x)*Math.min(1,dt*9);state.ship.position.y+=((r.y-.55)-state.ship.position.y)*Math.min(1,dt*9);r.answerDelay=Math.max(0,(r.answerDelay||0)-dt);$("#modeText").textContent="Answer Gates";$("#missionText").textContent=r.answerDelay>0?"Read the choices. Gates activate in "+Math.ceil(r.answerDelay)+".":"Fly through the best answer gate.";if(r.answerDelay>0){$$(".answer").forEach((el,i)=>el.classList.toggle("active",Math.abs(r.x-[-9,-3,3,9][i])<2.8));return}for(const g of state.gates){g.group.position.z+=dt*20;g.group.rotation.z+=dt*.55;const d=g.group.position.distanceTo(new THREE.Vector3(r.x,r.y,0));if(!g.hit&&g.group.position.z>-4&&d<3.6){chooseGate(g.i);return}if(!g.hit&&g.group.position.z>18){chooseGate(-1);return}}$$(".answer").forEach((el,i)=>el.classList.toggle("active",Math.abs(r.x-[-9,-3,3,9][i])<2.8))}
function chooseGate(index){if(state.phase!=="answer")return;engine(false);const q=currentQuestion(), choice=q.choices[index], ok=choice&&choice.label===q.correct;state.phase="feedback";for(const g of state.gates)state.scene.remove(g.group);state.gates=[];$$(".answer").forEach((el,i)=>{const label=q.choices[i]?.label;el.classList.toggle("good",label===q.correct);el.classList.toggle("bad",i===index&&!ok)});$("#hud").classList.add("hidden");$("#touchControls").classList.add("hidden");$("#answerPanel").classList.add("hidden");$("#feedbackPanel").classList.remove("hidden");const right=q.choices.find(c=>c.label===q.correct);if(ok){state.run.correct++;state.run.score+=1200;$("#feedbackTitle").textContent="Gate Locked";$("#feedbackBody").textContent="+1200 mission points. Correct answer: "+right.label+". "+right.text;tone("good")}else{state.run.hull-=16;state.run.missed.push(q);$("#feedbackTitle").textContent=index<0?"Gate Missed":"Wrong Gate";$("#feedbackBody").textContent="Correct answer: "+(right?right.label+". "+right.text:"Review this item.");tone("bad")}$("#feedbackExplain").textContent=q.explanation||"";updateHud()}
function continueFlight(){state.run.index++;if(state.run.index>=state.run.questions.length||state.run.hull<=0){finish();return}$("#feedbackPanel").classList.add("hidden");$("#hud").classList.remove("hidden");$("#touchControls").classList.remove("hidden");state.phase="flight";state.run.beaconDelay=2.2;state.run.flightClock=0;state.run.minFlight=9;state.run.checkpointReadyAt=performance.now()+9500;state.run.combo=0;makeBeacon();makeStorm();makeWaypoints();engine(true)}
function finish(){if(!state.run)return;engine(false);clearWaypoints();state.phase="summary";hidePanels();$("#hud").classList.add("hidden");$("#touchControls").classList.add("hidden");$("#summary").classList.remove("hidden");const r=state.run,acc=r.questions.length?Math.round(r.correct/r.questions.length*100):0;$("#summaryStats").innerHTML=[[r.score,"score"],[acc+"%","accuracy"],[Math.max(0,Math.round(r.hull))+"%","hull"]].map(m=>'<div class="stat"><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></div>').join("");$("#missedList").innerHTML=r.missed.length?r.missed.slice(0,8).map(q=>{const right=q.choices.find(c=>c.label===q.correct);return '<div class="missed-item"><b>'+esc(q.stem)+'</b><br>'+esc(q.set+" · "+q.source)+'<br><b>Correct:</b> '+esc(right?right.label+". "+right.text:"")+'<br>'+esc(q.explanation||"Review this source.")+'</div>'}).join(""):'<div class="missed-item"><b>No missed answer gates.</b><br>Try a longer mixed mission.</div>'}
function pause(){if(!state.run||state.phase==="setup")return;engine(false);state.phase="pause";$("#pausePanel").classList.remove("hidden");$("#hud").classList.add("hidden");$("#touchControls").classList.add("hidden")}
function resume(){if(!state.run)return;$("#pausePanel").classList.add("hidden");$("#hud").classList.remove("hidden");$("#touchControls").classList.remove("hidden");state.phase=$("#answerPanel").classList.contains("hidden")?"flight":"answer";engine(true)}
$("#courseSelect").addEventListener("change",e=>{state.course=e.target.value;state.set="All Sets";renderSets();renderPreview()});
$("#setSelect").addEventListener("change",e=>{state.set=e.target.value;renderPreview()});
$("#lengthSelect").addEventListener("change",e=>{state.length=Number(e.target.value);renderPreview()});
$("#assistSelect").addEventListener("change",e=>{state.assist=e.target.value==="1"});
$("#startBtn").addEventListener("click",start);$("#againBtn").addEventListener("click",start);$("#settingsBtn").addEventListener("click",()=>{hidePanels();$("#setup").classList.remove("hidden");state.phase="setup"});
$("#homeBtn").addEventListener("click",()=>location.href="../../index.html");$("#pauseBtn").addEventListener("click",pause);$("#resumeBtn").addEventListener("click",resume);$("#quitBtn").addEventListener("click",finish);$("#openGatesBtn").addEventListener("click",openGates);$("#continueBtn").addEventListener("click",continueFlight);
$("#leftBtn").addEventListener("pointerdown",()=>state.keys.ArrowLeft=true);$("#leftBtn").addEventListener("pointerup",()=>state.keys.ArrowLeft=false);$("#rightBtn").addEventListener("pointerdown",()=>state.keys.ArrowRight=true);$("#rightBtn").addEventListener("pointerup",()=>state.keys.ArrowRight=false);$("#upBtn").addEventListener("pointerdown",()=>state.keys.ArrowUp=true);$("#upBtn").addEventListener("pointerup",()=>state.keys.ArrowUp=false);$("#downBtn").addEventListener("pointerdown",()=>state.keys.ArrowDown=true);$("#downBtn").addEventListener("pointerup",()=>state.keys.ArrowDown=false);
addEventListener("keydown",e=>{state.keys[e.key]=true;if(e.key==="Escape")pause();if(["1","2","3","4"].includes(e.key)&&state.phase==="answer")chooseGate(Number(e.key)-1)});
addEventListener("keyup",e=>{state.keys[e.key]=false});
addEventListener("pointermove",e=>{if(state.phase==="flight"||state.phase==="answer")state.pointer={x:e.clientX/innerWidth,y:e.clientY/innerHeight}});
addEventListener("pointerleave",()=>state.pointer=null);
fetch("../../data/regents-gauntlet-bank.json?v=20260426-time-pilot-embedfix").then(r=>r.json()).then(bank=>{state.bank=bank;renderSetup()});
