import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.164.1/build/three.module.js";

const lanes=[-6,-2,2,6];
const state={bank:null,course:"All Courses",set:"All Sets",length:20,speedMod:1,pool:[],run:null,scene:null,camera:null,renderer:null,player:null,road:null,rings:[],stars:null,gate:null,pickups:[],hazards:[],lastTime:0,raf:0,paused:false,ready:false,audio:null};
const $=s=>document.querySelector(s);
const $$=s=>Array.from(document.querySelectorAll(s));
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function uniq(a){return Array.from(new Set(a.filter(Boolean))).sort((x,y)=>x.localeCompare(y,undefined,{numeric:true}))}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function shuffle(a){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function tone(kind){try{state.audio=state.audio||new (window.AudioContext||window.webkitAudioContext)();const c=state.audio,o=c.createOscillator(),g=c.createGain(),now=c.currentTime;const map={start:[196,392,.16,"triangle"],ok:[540,930,.14,"sine"],bad:[160,92,.2,"sawtooth"],coin:[840,1220,.08,"triangle"],hit:[120,70,.12,"square"]};const m=map[kind]||map.ok;o.type=m[3];o.frequency.setValueAtTime(m[0],now);o.frequency.exponentialRampToValueAtTime(m[1],now+m[2]);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(kind==="bad"?.052:.03,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+m[2]);o.connect(g);g.connect(c.destination);o.start();o.stop(now+m[2]+.03)}catch(e){}}
function questions(){return state.bank.questions.filter(q=>(state.course==="All Courses"||q.course===state.course)&&(state.set==="All Sets"||q.set===state.set))}
function balancedPick(items,count){const groups=new Map();shuffle(items).forEach(q=>{const key=q.set||q.course;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(q)});const picked=[];while(picked.length<count&&Array.from(groups.values()).some(g=>g.length)){for(const group of groups.values()){if(group.length&&picked.length<count)picked.push(group.pop())}}return picked}
function renderSetup(){const qs=state.bank.questions;$("#stats").innerHTML=[[qs.length,"answer gates"],[uniq(qs.map(q=>q.set)).length,"review sets"],[qs.filter(q=>(q.stimulusImages||[]).length).length,"source shards"]].map(m=>'<div class="stat"><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></div>').join("");$("#courseSelect").innerHTML=["All Courses"].concat(uniq(qs.map(q=>q.course))).map(c=>'<option>'+esc(c)+'</option>').join("");renderSetOptions();renderPreview()}
function renderSetOptions(){const sets=uniq(state.bank.questions.filter(q=>state.course==="All Courses"||q.course===state.course).map(q=>q.set));$("#setSelect").innerHTML=["All Sets"].concat(sets).map(s=>'<option>'+esc(s)+'</option>').join("");if(!["All Sets"].concat(sets).includes(state.set))state.set="All Sets";$("#setSelect").value=state.set}
function renderPreview(){const qs=questions();const count=Math.min(state.length,qs.length);$("#preview").innerHTML='<strong>'+esc(count)+' answer portals queued</strong><br>'+esc(qs.length)+' available from '+esc(state.course)+' · '+esc(state.set)+'.<br>Steer with arrows, A/D, swipes, bottom buttons, or tap a choice card to jump lanes.'}
function initThree(){if(state.ready)return;const canvas=$("#stage");state.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:"high-performance"});state.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));state.renderer.setSize(innerWidth,innerHeight);state.scene=new THREE.Scene();state.scene.fog=new THREE.FogExp2(0x020713,.028);state.camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,230);state.camera.position.set(0,6.5,14);state.camera.lookAt(0,0,-28);
  const amb=new THREE.AmbientLight(0x86dfff,.8), key=new THREE.DirectionalLight(0xffdd9a,1.8), rim=new THREE.PointLight(0x66f3ff,3,80);key.position.set(-8,12,10);rim.position.set(0,4,-16);state.scene.add(amb,key,rim);
  const roadGeo=new THREE.PlaneGeometry(18,240,1,1), roadMat=new THREE.MeshStandardMaterial({color:0x061024,metalness:.78,roughness:.28,transparent:true,opacity:.82});state.road=new THREE.Mesh(roadGeo,roadMat);state.road.rotation.x=-Math.PI/2;state.road.position.z=-70;state.scene.add(state.road);
  for(const x of lanes){const line=new THREE.Mesh(new THREE.BoxGeometry(.08,.04,240),new THREE.MeshBasicMaterial({color:x<0?0x67f3ff:0xffd36c,transparent:true,opacity:.72}));line.position.set(x,-.02,-70);state.scene.add(line)}
  state.rings=Array.from({length:18},(_,i)=>{const ring=new THREE.Mesh(new THREE.TorusGeometry(9.7,.055,10,96),new THREE.MeshBasicMaterial({color:i%3===0?0xffd36c:0x67f3ff,transparent:true,opacity:.48}));ring.position.z=-i*12-8;ring.rotation.x=Math.PI/2;state.scene.add(ring);return ring});
  const starGeo=new THREE.BufferGeometry(), pts=[];for(let i=0;i<700;i++)pts.push((Math.random()-.5)*90,Math.random()*42-6,-Math.random()*180);starGeo.setAttribute("position",new THREE.Float32BufferAttribute(pts,3));state.stars=new THREE.Points(starGeo,new THREE.PointsMaterial({color:0x90f6ff,size:.08,transparent:true,opacity:.78}));state.scene.add(state.stars);
  state.player=makePlayer();state.scene.add(state.player);state.ready=true;addEventListener("resize",resize)}
function makePlayer(){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.ConeGeometry(.75,2.15,5),new THREE.MeshStandardMaterial({color:0x67f3ff,emissive:0x103c44,metalness:.62,roughness:.2}));body.rotation.x=Math.PI/2;const core=new THREE.Mesh(new THREE.SphereGeometry(.38,18,18),new THREE.MeshBasicMaterial({color:0xffd36c}));core.position.z=.15;const wingMat=new THREE.MeshStandardMaterial({color:0xff62ce,emissive:0x2a0620,metalness:.44,roughness:.25});const wingL=new THREE.Mesh(new THREE.BoxGeometry(1.35,.08,.55),wingMat), wingR=wingL.clone();wingL.position.set(-.72,0,.1);wingR.position.set(.72,0,.1);g.add(body,core,wingL,wingR);g.position.set(lanes[1],.7,3.5);return g}
function makeGate(q){const group=new THREE.Group();group.position.z=-82;const labels=q.choices.map(c=>c.label);for(let i=0;i<4;i++){const choice=q.choices[i];const ok=choice.label===q.correct;const ring=new THREE.Mesh(new THREE.TorusGeometry(1.22,.08,12,42),new THREE.MeshBasicMaterial({color:ok?0x67f3ff:0x557096,transparent:true,opacity:.92}));ring.position.set(lanes[i],2.25,0);ring.userData={label:choice.label,ok};const panel=new THREE.Sprite(new THREE.SpriteMaterial({map:textTexture(choice.label+". "+choice.text,ok),transparent:true,opacity:.95}));panel.position.set(lanes[i],3.85,.05);panel.scale.set(3.25,1.18,1);group.add(ring,panel)}state.scene.add(group);return {group,q,labels,passed:false}}
function textTexture(text,accent){const c=document.createElement("canvas");c.width=1024;c.height=384;const ctx=c.getContext("2d");ctx.fillStyle=accent?"rgba(255,211,108,.92)":"rgba(8,16,34,.88)";ctx.strokeStyle=accent?"rgba(255,255,255,.9)":"rgba(103,243,255,.82)";ctx.lineWidth=8;round(ctx,14,14,996,356,34);ctx.fill();ctx.stroke();ctx.fillStyle=accent?"#120d04":"#f7fbff";ctx.font="900 48px system-ui, sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";wrap(ctx,text,512,192,860,58);const t=new THREE.CanvasTexture(c);t.anisotropy=4;return t}
function round(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function wrap(ctx,text,x,y,max,lineH){const words=String(text).split(" "),lines=[];let line="";for(const word of words){const test=line?line+" "+word:word;if(ctx.measureText(test).width>max&&line){lines.push(line);line=word}else line=test}lines.push(line);const trimmed=lines.slice(0,4);if(lines.length>4)trimmed[3]=trimmed[3].replace(/\s+\S+$/,"")+"...";const top=y-(trimmed.length-1)*lineH/2;trimmed.forEach((l,i)=>ctx.fillText(l,x,top+i*lineH))}
function makePickup(z,lane){const m=new THREE.Mesh(new THREE.OctahedronGeometry(.42,0),new THREE.MeshBasicMaterial({color:0xffd36c}));m.position.set(lanes[lane],1.1,z);state.scene.add(m);return {mesh:m,lane,hit:false}}
function makeHazard(z,lane){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.68,1),new THREE.MeshStandardMaterial({color:0xff5970,emissive:0x2f0208,roughness:.4}));m.position.set(lanes[lane],1.1,z);state.scene.add(m);return {mesh:m,lane,hit:false}}
function resize(){if(!state.renderer)return;state.camera.aspect=innerWidth/innerHeight;state.camera.updateProjectionMatrix();state.renderer.setSize(innerWidth,innerHeight)}
function start(){initThree();const pool=questions();state.pool=balancedPick(pool,Math.min(state.length,pool.length));state.run={index:0,lane:1,score:0,streak:0,best:0,shields:5,correct:0,missed:[],gates:0,distance:0,damageCooldown:0};state.paused=false;$("#setup").classList.add("hidden");$("#summary").classList.add("hidden");$("#hud").classList.remove("hidden");$("#mobileControls").classList.remove("hidden");clearWorld();nextGate();renderHud();tone("start");state.lastTime=performance.now();cancelAnimationFrame(state.raf);state.raf=requestAnimationFrame(loop)}
function clearWorld(){if(state.gate){state.scene.remove(state.gate.group);state.gate=null}for(const p of state.pickups)state.scene.remove(p.mesh);for(const h of state.hazards)state.scene.remove(h.mesh);state.pickups=[];state.hazards=[]}
function nextGate(){const q=state.pool[state.run.index%state.pool.length];state.gate=makeGate(q);state.pickups=[];state.hazards=[];for(let i=0;i<8;i++){const z=-18-i*8-Math.random()*4;state.pickups.push(makePickup(z,Math.floor(Math.random()*4)))}for(let i=0;i<2;i++){const z=-32-i*18-Math.random()*5;let lane=Math.floor(Math.random()*4);if(state.run.gates<2&&lane===state.run.lane)lane=(lane+1)%4;state.hazards.push(makeHazard(z,lane))}renderQuestion(q)}
function renderQuestion(q){$("#missionText").textContent=q.course+" · "+q.day+" · Gate "+(state.run.index+1)+"/"+state.pool.length;$("#questionText").textContent=q.stem;$("#choiceDock").innerHTML=q.choices.map((c,i)=>'<button class="choice '+(i===state.run.lane?"active":"")+'" type="button" data-lane="'+i+'"><b>Lane '+(i+1)+'</b><span>'+esc(c.label)+'. '+esc(c.text)+'</span></button>').join("");$$(".choice").forEach(btn=>btn.addEventListener("click",()=>setLane(Number(btn.dataset.lane))));$("#sourceBtn").disabled=!(q.stimulusImages||[]).length}
function renderHud(){const r=state.run;if(!r)return;$("#scoreText").textContent=r.score;$("#streakText").textContent=r.streak;$("#shieldText").textContent=r.shields;$$(".choice").forEach((btn,i)=>btn.classList.toggle("active",i===r.lane))}
function setLane(lane){if(!state.run)return;state.run.lane=clamp(lane,0,3);renderHud()}
function moveLane(dir){setLane((state.run?.lane??1)+dir)}
function loop(now){const dt=Math.min(.033,(now-state.lastTime)/1000||.016);state.lastTime=now;if(!state.paused&&state.run){update(dt);state.renderer.render(state.scene,state.camera)}state.raf=requestAnimationFrame(loop)}
function update(dt){const r=state.run;const speed=(8.8+r.gates*.48)*state.speedMod;const move=speed*dt;r.distance+=move;r.score+=Math.floor(move*.8);state.player.position.x+=(lanes[r.lane]-state.player.position.x)*Math.min(1,dt*12);state.player.rotation.z=(lanes[r.lane]-state.player.position.x)*-.045;state.player.rotation.y=Math.sin(performance.now()*.006)*.07;
  for(const ring of state.rings){ring.position.z+=move;if(ring.position.z>12)ring.position.z-=216;ring.rotation.z+=dt*.18}
  if(state.stars)state.stars.rotation.y+=dt*.018;
  if(state.gate){state.gate.group.position.z+=move;state.gate.group.rotation.z+=dt*.06;if(state.gate.group.position.z>3&&!state.gate.passed)evaluateGate()}
  for(const p of state.pickups){p.mesh.position.z+=move;p.mesh.rotation.y+=dt*3;p.mesh.rotation.x+=dt*2;if(!p.hit&&p.mesh.position.z>2.2&&p.mesh.position.z<4.7&&p.lane===r.lane){p.hit=true;p.mesh.visible=false;r.score+=75+r.streak*12;toast("Energy collected","+speed charge",650);tone("coin")}}
  r.damageCooldown=Math.max(0,r.damageCooldown-dt);for(const h of state.hazards){h.mesh.position.z+=move;h.mesh.rotation.x+=dt*1.8;if(!h.hit&&r.damageCooldown<=0&&h.mesh.position.z>2.2&&h.mesh.position.z<4.8&&h.lane===r.lane){h.hit=true;h.mesh.visible=false;r.damageCooldown=1.2;r.shields--;r.streak=0;toast("Rift hazard","Shield damaged",900);tone("hit");if(r.shields<=0)finish()}}
  renderHud()}
function evaluateGate(){const r=state.run,g=state.gate,q=g.q;g.passed=true;r.gates++;const selected=q.choices[r.lane];const ok=selected&&selected.label===q.correct;$$(".choice").forEach((btn,i)=>{const label=q.choices[i]?.label;btn.classList.toggle("correct",label===q.correct);btn.classList.toggle("wrong",i===r.lane&&!ok)});if(ok){r.correct++;r.streak++;r.best=Math.max(r.best,r.streak);r.score+=450+r.streak*90;toast("Portal locked","+ "+(450+r.streak*90)+" points",900);tone("ok")}else{r.shields--;r.streak=0;r.missed.push(q);const right=q.choices.find(c=>c.label===q.correct);toast("Wrong portal",(right?right.label+". "+right.text:"Review this clue"),1600);tone("bad")}if(r.shields<=0){finish();return}r.index++;if(r.index>=state.pool.length){finish();return}setTimeout(()=>{if(state.run&&!state.paused){state.scene.remove(g.group);for(const p of state.pickups)state.scene.remove(p.mesh);for(const h of state.hazards)state.scene.remove(h.mesh);nextGate()}},850)}
function toast(title,body,ms){$("#toast").innerHTML='<strong>'+esc(title)+'</strong><p>'+esc(body)+'</p>';$("#toast").classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>$("#toast").classList.add("hidden"),ms)}
function finish(){if(!state.run)return;cancelAnimationFrame(state.raf);const r=state.run;$("#hud").classList.add("hidden");$("#mobileControls").classList.add("hidden");$("#pausePanel").classList.add("hidden");$("#summary").classList.remove("hidden");const acc=r.gates?Math.round(r.correct/r.gates*100):0;$("#summaryStats").innerHTML=[[r.score,"score"],[acc+"%","portal accuracy"],[r.best,"best streak"]].map(m=>'<div class="stat"><strong>'+esc(m[0])+'</strong><span>'+esc(m[1])+'</span></div>').join("");$("#missedList").innerHTML=r.missed.length?r.missed.slice(0,8).map(q=>{const right=q.choices.find(c=>c.label===q.correct);return '<div class="missed-item"><b>'+esc(q.stem)+'</b><br>'+esc(q.set+" · "+q.source)+'<br><b>Correct:</b> '+esc(right?right.label+". "+right.text:"")+'<br>'+esc(q.explanation||"Review this source.")+'</div>'}).join(""):'<div class="missed-item"><b>No missed portals.</b><br>Try a faster run or a longer course mix.</div>';state.run=null}
function pause(){if(!state.run)return;state.paused=true;$("#pauseMeta").textContent="Score "+state.run.score+" · streak "+state.run.streak;$("#pausePanel").classList.remove("hidden")}
function resume(){state.paused=false;$("#pausePanel").classList.add("hidden");state.lastTime=performance.now()}
function showSource(){if(!state.gate)return;const q=state.gate.q, imgs=q.stimulusImages||[];$("#sourceTitle").textContent=q.source||"Original source page";$("#sourceImages").innerHTML=imgs.length?imgs.map((img,i)=>'<figure><img src="'+esc(img.src)+'" alt="'+esc(img.label||("Source page "+(i+1)))+'"><figcaption>'+esc(img.label||("Source page "+(i+1)))+'</figcaption></figure>').join(""):'<div class="preview">No source image for this gate.</div>';$("#sourcePanel").classList.remove("hidden");state.paused=true}
$("#courseSelect").addEventListener("change",e=>{state.course=e.target.value;state.set="All Sets";renderSetOptions();renderPreview()});
$("#setSelect").addEventListener("change",e=>{state.set=e.target.value;renderPreview()});
$("#lengthSelect").addEventListener("change",e=>{state.length=Number(e.target.value);renderPreview()});
$("#speedSelect").addEventListener("change",e=>{state.speedMod=Number(e.target.value)});
$("#startBtn").addEventListener("click",start);$("#againBtn").addEventListener("click",start);$("#settingsBtn").addEventListener("click",()=>{$("#summary").classList.add("hidden");$("#setup").classList.remove("hidden")});
$("#arcadeBtn").addEventListener("click",()=>location.href="../../index.html");$("#pauseBtn").addEventListener("click",pause);$("#resumeBtn").addEventListener("click",resume);$("#endBtn").addEventListener("click",finish);
$("#sourceBtn").addEventListener("click",showSource);$("#closeSourceBtn").addEventListener("click",()=>{$("#sourcePanel").classList.add("hidden");state.paused=false;state.lastTime=performance.now()});
$("#leftBtn").addEventListener("click",()=>moveLane(-1));$("#rightBtn").addEventListener("click",()=>moveLane(1));
addEventListener("keydown",e=>{if(e.key==="ArrowLeft"||e.key.toLowerCase()==="a")moveLane(-1);if(e.key==="ArrowRight"||e.key.toLowerCase()==="d")moveLane(1);if(e.key==="Escape")state.paused?resume():pause();if(["1","2","3","4"].includes(e.key))setLane(Number(e.key)-1)});
let touchX=0;addEventListener("touchstart",e=>{touchX=e.changedTouches[0].clientX},{passive:true});addEventListener("touchend",e=>{const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>32)moveLane(dx>0?1:-1)},{passive:true});
fetch("../../data/regents-gauntlet-bank.json?v=20260426-chrono-rift").then(r=>r.json()).then(bank=>{state.bank=bank;renderSetup();initThree();state.renderer.render(state.scene,state.camera)});
